README.md
While we create a proper Readme, just add a basic readme with basic steps to run the project
=> Add basic Readme

.travis.yml, Bow.xcodeproj/xcshareddata/xcschemes/Bow.xcscheme
Added Support in Travis in order to enable Code Coverage support.
close #13
=> Code cov support

README.md
=> Added Travis and CodeCov Tags

Bow.xcworkspace/contents.xcworkspacedata, BowPlayground.playground/Pages/Play.xcplaygroundpage/Contents.swift, BowPlayground.playground/contents.xcplayground
With the purpose of making the development and the tests more comfortable, I modified the project to add a workspace with a playground. 
In this PR I only add a playground page to do tests while developing but we could use them as documentation also.
=> Added a playground to test

Bow.xcodeproj/project.pbxproj, Bow.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Sources/Bow/Data/ListK.swift, Sources/Bow/Optics/Fold.swift, Sources/Bow/Optics/Getter.swift, Sources/Bow/Optics/Iso.swift, Sources/Bow/Optics/Lens.swift, Sources/Bow/Optics/Optional.swift, Sources/Bow/Optics/Prism.swift, Sources/Bow/Optics/Setter.swift, Sources/Bow/Optics/Traversal.swift, Sources/Bow/Optics/Typeclasses/Each.swift, Sources/Bow/Optics/Typeclasses/FilterIndex.swift, Tests/BowTests/Optics/IsoTest.swift, Tests/BowTests/Optics/Laws/TraversalLaws.swift, Tests/BowTests/Optics/LensTest.swift, Tests/BowTests/Optics/OptionalTest.swift, Tests/BowTests/Optics/PrismTest.swift
Pull request #24 addressed an initial implementation for some of the optics present in Arrow. This PR completes the list with: 
- Implementation of Fold and Traversal.
- Conversions and compositions between each optics. 
- Laws for Traversal and tests for these laws.
There are still some tests missing for each optic to make sure they work properly.
=> Missing optics

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/ListK.swift, Sources/Bow/Data/NonEmptyList.swift, Sources/Bow/Optics/DSL/At+Optics.swift, Sources/Bow/Optics/DSL/Each+Optics.swift, Sources/Bow/Optics/Instances/EitherOpticsInstances.swift, Sources/Bow/Optics/Instances/ListKOpticsInstances.swift, Sources/Bow/Optics/Instances/MaybeOpticsInstances.swift, Sources/Bow/Optics/Instances/NonEmptyListOpticsInstances.swift, Sources/Bow/Optics/Instances/StringOpticsInstances.swift, Sources/Bow/Optics/Instances/TryOpticsInstances.swift, Sources/Bow/Optics/Typeclasses/FilterIndex.swift
This PR adds instances of several optics for:
- Either
- ListK
- NonEmptyList
- Maybe
- String
- Try
The rest of data types still need to be finished before we can provide instances for optics.
=> Optics instances

.travis.yml, scripts/push.sh
I have to test it first, but it should release a new version of the library when pushing a new tag. 
You would have to manually update the version number in the project and in the .podspec tho.
I would like to include fastlane to handle all of this too :)
=> Configure travis to make a new release when pushing a tag

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/ListK.swift, Sources/Bow/Data/Maybe.swift, Tests/BowTests/Optics/FoldTest.swift, Tests/BowTests/Optics/GetterTest.swift, Tests/BowTests/Optics/IsoTest.swift, Tests/BowTests/Optics/Laws/SetterLaws.swift, Tests/BowTests/Optics/Laws/TraversalLaws.swift, Tests/BowTests/Optics/LensTest.swift, Tests/BowTests/Optics/OptionalTest.swift, Tests/BowTests/Optics/PrismTest.swift, Tests/BowTests/Optics/SetterTest.swift, Tests/BowTests/Optics/TestDomain.swift, Tests/BowTests/Optics/TraversalTest.swift
This PR adds tests properties of all Optics, as well as checks the composition between each other works as expected.
=> Test Optics

Bow.podspec, LICENSE
Adds Apache License 2.0. Closes #41.
=> Add license

Bow.xcodeproj/project.pbxproj, Package.resolved, Package.swift, README.md
Issue: #67 
Package Manager definition was wrong, this PR updates it and also removes some unneeded dependencies from some test targets. 
I tested it locally and both commands are working, `swift build` and `swift test`.
```Test Suite 'WriterTTest' passed at 2018-11-22 19:28:46.533.
Executed 11 tests, with 0 failures (0 unexpected) in 0.436 (0.437) seconds
Test Suite 'BowPackageTests.xctest' passed at 2018-11-22 19:28:46.533.
Executed 367 tests, with 0 failures (0 unexpected) in 20.383 (20.411) seconds
Test Suite 'All tests' passed at 2018-11-22 19:28:46.533.
Executed 367 tests, with 0 failures (0 unexpected) in 20.383 (20.412) seconds```
=> Fix package manager

Sources/Bow/Data/Id.swift
This PR adds API docs to the `Id<A>` data type. Closes #88.
=> Add API documentation to Id

docs/_config.yml, docs/_includes/_google-tag-manager.html, docs/_includes/_head.html
* Add Google Analytics to the page 😔
This closes #87
=> Add Google Analytics to the page 😔

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add templates for issues and pull requests

Sources/Bow/Instances/BoolInstances.swift
=> Add docs to BoolInstances

Sources/Bow/Instances/NumberInstances.swift
Closes #98.
Add API reference to each class in `NumberInstances`.
=> Add docs to NumberInstances

Sources/Bow/Typeclasses/Monoid.swift, Sources/Bow/Typeclasses/Semigroup.swift
- Closes #140.
- Closes #141.
- Write API docs for Semigroup.
- Write API docs for Monoid.
=> Semigroup and Monoid docs

Sources/Bow/Arrow/Function1.swift
- Closes #171.
Add API docs for Function1.
=> Add docs for Function1

Sources/Bow/Arrow/Function0.swift
- Closes #169 
Add docs for Function0.
=> Add docs for Function0

Sources/Bow/Typeclasses/ApplicativeError.swift, Sources/Bow/Typeclasses/MonadError.swift
- Closes #162.
- Closes #163.
Add API docs for ApplicativeError and MonadError.
=> API docs for ApplicativeError and MonadError

Sources/Bow/Typeclasses/Bimonad.swift, Sources/Bow/Typeclasses/Comonad.swift
- Closes #159.
- Closes #160.
Add API docs for Comonad and Bimonad.
=> API docs for Comonad and Bimonad

Sources/Bow/Typeclasses/Comparable.swift, Sources/Bow/Typeclasses/EquatableK.swift
- Closes #156.
- Closes #157.
Add API docs for EquatableK and Comparable.
=> API docs for EquatableK and Comparable

Sources/Bow/Typeclasses/Contravariant.swift
- Closes #186 
Add API docs for Contravariant.
=> Add API docs for Contravariant

Sources/Bow/Typeclasses/Foldable.swift, Sources/Bow/Typeclasses/Traverse.swift
- Closes #188.
- Closes #189.
Add API docs for `Foldable` and `Traverse`.
=> Add API docs for Foldable and Traverse

Sources/Bow/Typeclasses/Reducible.swift
- Closes #190.
Add API docs for `Reducible`.
=> Add API docs for Reducible

Sources/Bow/Arrow/Kleisli.swift, Sources/Bow/Data/Reader.swift
- Closes #201.
Add API docs for Kleisli.
=> Add API docs for Kleisli

Sources/Bow/Data/Coproduct.swift
- Closes #202 
Add API docs for Coproduct.
=> Add API docs for Coproduct

Sources/Bow/Data/Try.swift
- Closes #121 
Add API docs for Try
=> Add API docs for Try

Sources/Bow/Transformers/EitherT.swift
- Closes #206 
Add API docs for `EitherT`.
=> Add API docs for EitherT

Sources/Bow/Transformers/OptionT.swift
- Closes #206 
Add API docs for `EitherT`.
=> Add API docs for OptionT

Sources/Bow/Data/State.swift, Sources/Bow/Transformers/StateT.swift
- Closes #208 
Add API docs for `StateT` and `State`.
=> Add API docs for StateT and State

Sources/Bow/Transformers/WriterT.swift
- Close #209 
Add API docs for `WriterT`.
=> Add API docs for WriterT

Sources/Bow/Data/ArrayK.swift
- Closes #117.
Add API docs for `ArrayK`.
=> Add API docs for ArrayK

Sources/Bow/Data/DictionaryK.swift
- Closes #118 
Add API docs for `DictionaryK`.
=> Add API docs for DictionaryK

Sources/Bow/Data/NonEmptyArray.swift
- Closes #119 
Add API docs for `NonEmptyArray`.
=> Add API docs for NonEmptyArray

Sources/Bow/Data/Ior.swift
- Closes #116.
Add API docs for `Ior`.
=> Add API docs for Ior

Sources/Bow/Arrow/Cokleisli.swift, Sources/Bow/Data/Coreader.swift
- Closes #219 
Add API docs for Cokleisli and Coreader.
=> Add API docs for Cokleisli and Coreader

Sources/Bow/Data/Either.swift, Sources/Bow/Transformers/OptionT.swift, Tests/BowTests/Transformers/OptionTTest.swift
Closes: #239 
Add missing methods compared to Arrow version.
=> Add missing functions to OptionT

docs/_data/menu.yml, docs/_includes/_footer.html, docs/_includes/_head.html, docs/_includes/_nav.html, docs/_sass/components/_footer.scss, docs/_sass/components/_navigation.scss
#312 
In order to fix the Google usability issues report when Bow site is in mobile view, we add icons in the nav bar and footer and make footer `font-size` bigger.
=> Review mobile usability

Sources/Bow/Data/Either.swift
- Closes #222 
Add missing methods compared to Arrow version.
=> Add missing functions to Either

.travis.yml, contents/Documentation/FP concepts.playground/Pages/Data types.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Functions vs Procedures.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Glossary.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Higher Kinded Types.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Type classes.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/contents.xcplayground, contents/Documentation/Legal.playground/Pages/Credits.xcplaygroundpage/Contents.swift, contents/Documentation/Podfile, contents/Documentation/Podfile.lock
Provide some documentation for FP core concepts that are addressed in the library.
Pages for the following content have been written:
- Functions vs Procedures: includes notions on what is FP, what is a function and benefits of programming with them.
- Higher Kinded Types: includes definitions and motivation, how they are implemented in Bow, and how you can make your own HKT.
- Type classes: includes definitions, how they are used, and the core ones provided in Bow.
- Data types: includes definitions, how they are used, and the core ones provided in Bow.
- Glossary: acts as a dictionary of recurring terms that are used across the docs.
=> Docs for FP concepts

contents/Documentation/FP concepts.playground/Pages/Higher Kinded Types.xcplaygroundpage/Contents.swift
Remove open nef tag without matching closing tag.
=> Fix wrong nef tags

contents/Documentation/FP concepts.playground/Pages/Higher Kinded Types.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/contents.xcplayground
Link `Data types` page to show it in the documentation.
=> Link missing page

BowRx.podspec, README.md, contents/Documentation/Quick start.playground/Pages/Modules.xcplaygroundpage/Contents.swift, scripts/gen-docs.rb
- Added new logo
- Updated cocoapods dependencies
=> New branding

README.md, docs/_includes/_header.html, docs/_sass/components/_buttons.scss, docs/_sass/components/_features.scss, docs/_sass/components/_masthead.scss, docs/img/logo_masthead.svg
Fix some problems when rendering the site, specially in mobile viewports.
=> Bow rebrandig mobile

Bow-BrightFuturesGenerators-Info.plist, Bow-Effects-Generators-Info.plist, Bow-Free-Generators-Info.plist, Bow-RxGenerators-Info.plist, Bow.xcodeproj/project.pbxproj, Bow.xcodeproj/xcshareddata/xcschemes/Bow-BrightFutures-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Effects-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Free-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Rx-Generators.xcscheme, Sources/BowBrightFutures/FutureK.swift, Sources/BowRx/MaybeK.swift, Sources/BowRx/ObservableK.swift, Sources/BowRx/SingleK.swift, Tests/BowBrightFuturesGenerators/FutureK+Gen.swift, Tests/BowEffectsGenerators/IO+Gen.swift, Tests/BowFreeGenerators/Free+Gen.swift, Tests/BowRxGenerators/MaybeK+Gen.swift, Tests/BowRxGenerators/ObservableK+Gen.swift, Tests/BowRxGenerators/SingleK+Gen.swift
Add generators for other types outside the core module.
Based on the work done in #336, we extend it to create PBT generators for Effects, Rx, BrightFutures and Free.
=> Generators for Effects, Rx, BrightFutures and Free

contents/Documentation/Documentation.xcodeproj/project.pbxproj, contents/Documentation/Patterns.playground/Pages/Error handling.xcplaygroundpage/Contents.swift, contents/Documentation/Patterns.playground/contents.xcplayground, contents/Documentation/Podfile.lock, docs/index.md
Adds an article to the docs with an exhaustive description of error handling in a functional way. The article is based on [my talk on this topic](https://truizlop.github.io/DataValidationBow/#/).
=> Add error handling docs

Bow.xcodeproj/xcshareddata/xcschemes/Bow-BrightFutures-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Free-Generators.xcscheme, Sources/Bow/Typeclasses/Foldable.swift, Sources/Bow/Typeclasses/Reducible.swift, Tests/BowLaws/EquatableKLaws.swift, Tests/BowLaws/EquatableLaws.swift, Tests/BowLaws/FoldableLaws.swift, Tests/BowLaws/MonadFilterLaws.swift, Tests/BowLaws/MonoidKLaws.swift, Tests/BowLaws/TraverseLaws.swift
- Closes #273 
- Closes #274 
- Closes #275 
- Closes #276 
- Closes #277 
Add missing laws for some type classes at the core module with respect to Arrow.
=> Add missing laws

Sources/Bow/Arrow/Kleisli.swift, Sources/Bow/Data/Option.swift, Sources/Bow/Data/Validated.swift, Sources/Bow/Transformers/EitherT.swift, Sources/Bow/Transformers/StateT.swift, Sources/Bow/Typeclasses/ApplicativeError.swift, Sources/BowFree/Free.swift, Tests/BowTests/Data/ValidatedTest.swift
- Closes #224
- Closes #237
- Closes #238
- Closes #240
- Closes #241
- Closes #278
- Closes #284
Add some missing functions to some types with respect to their Arrow counterpart.
=> Add missing functions

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/ArrayK.swift, Sources/BowOptics/Instances/ArrayKOpticsInstances.swift, Sources/BowOptics/Typeclasses/At.swift, Sources/BowOptics/Typeclasses/Cons.swift, Sources/BowOptics/Typeclasses/Each.swift, Sources/BowOptics/Typeclasses/FilterIndex.swift, Sources/BowOptics/Typeclasses/Index.swift, Sources/BowOptics/Typeclasses/Snoc.swift
- Closes #299 
- Closes #300 
- Closes #310 
Provide new type classes and instances to work with optics.
- Cons and Snoc type classes have been added.
- Instances of these type classes for ArrayK have been added.
=> Add Cons and Snoc type classes for optics

Sources/BowOptics/Typeclasses/At.swift, Sources/BowOptics/Typeclasses/Cons.swift, Sources/BowOptics/Typeclasses/Each.swift, Sources/BowOptics/Typeclasses/FilterIndex.swift, Sources/BowOptics/Typeclasses/Index.swift, Sources/BowOptics/Typeclasses/Snoc.swift
- Closes #356 
Add API reference to the following type classes:
- At
- Each
- Cons
- FilterIndex
- Index
- Snoc
=> Add API reference to optics type classes

Sources/BowOptics/Getter.swift, Sources/BowOptics/Lens.swift, Sources/BowOptics/Optional.swift, Sources/BowOptics/Traversal.swift
- Closes #302
- Closes #303
- Closes #304
- Closes #305
Add some missing functions to the optics.
=> Missing functions in optics

Sources/BowOptics/DSL/At+Optics.swift, Sources/BowOptics/DSL/Each+Optics.swift, Sources/BowOptics/DSL/Index+Optics.swift, Sources/BowOptics/DSL/Kind+Optics.swift
- Closes #358 
Add API reference for optics DSL.
=> Add API reference for optics DSL

Sources/BowOptics/Fold.swift, Sources/BowOptics/Getter.swift, Sources/BowOptics/Iso.swift, Sources/BowOptics/Lens.swift, Sources/BowOptics/Optional.swift, Sources/BowOptics/Prism.swift, Sources/BowOptics/Setter.swift, Sources/BowOptics/Traversal.swift, Tests/BowOpticsTests/FoldTest.swift, Tests/BowOpticsTests/GetterTest.swift, Tests/BowOpticsTests/IsoTest.swift, Tests/BowOpticsTests/LensTest.swift, Tests/BowOpticsTests/OptionalTest.swift, Tests/BowOpticsTests/PrismTest.swift, Tests/BowOpticsTests/SetterTest.swift, Tests/BowOpticsTests/TestDomain.swift, Tests/BowOpticsTests/TraversalTest.swift
- Closes #367 
Adds API reference for Iso.
=> Add API reference for Iso

Bow.xcodeproj/project.pbxproj, Sources/BowEffects/Data/Resource.swift, Sources/BowEffects/Utilities/UnitDuration+Extension.swift
- Closes #264 
- Closes #270 
- Implements new time units as an extension of `UnitDuration`.
- Implements `Resource` class to handle acquiring and releasing resources properly.
=> Add Resource and new UnitDurations

Sources/BowOptics/Lens.swift
- Closes #368.
Add API reference for Lens.
=> Add API reference for Lens

Sources/BowOptics/Getter.swift
- Closes #366 
Add API documentation for `Getter`.
=> Add API docs for Getter

Sources/BowOptics/BoundSetter.swift, Sources/BowOptics/Setter.swift
- Closes #364 
- Closes #371 
Add API reference for `Setter` and `BoundSetter`.
=> Add API docs for Setter and BoundSetter

docs/_includes/_navigation-api-versions.html, docs/_includes/_navigation-doc-versions.html, docs/_includes/_sidebar-doc-versions.html
#315 
A bad URL formation has been introduced as part of #334. This PR aims to fix that.
=> Add a leading slash to have URLs as absolute

Sources/BowOptics/Optional.swift
- Closes #369.
Add API documentation for `POptional`.
=> Add API reference for Optional

Sources/BowOptics/Traversal.swift
- Closes #372.
Add API documentation for `Traversal`.
=> Add API reference for Traversal

Sources/BowOptics/Fold.swift
- Closes #365.
Add API reference for `Fold`.
=> Add API reference for Fold

Sources/BowOptics/Prism.swift
- Closes #370.
Add API reference for `Prism`.
=> Add API reference for Prism

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/ArrayK.swift, Sources/Bow/Data/Eval.swift, Sources/Bow/Typeclasses/Foldable.swift, Sources/BowFree/Cofree.swift, Sources/BowRecursionSchemes/Recursion.swift, Sources/BowRx/MaybeK.swift, Sources/BowRx/ObservableK.swift, Tests/BowGenerators/Data/Eval+Gen.swift, Tests/BowTests/Data/EvalTest.swift
- Closes #298 
Guarantee the `Eval` data type is correct. Previous implementation was not tested and was faulty. It has been refactored and tests for its instances have been added. Also, missing instances (`Comonad` and `Bimonad`) are added as part of this PR.
=> Refactor Eval

Bow.xcodeproj/project.pbxproj, Sources/BowEffects/Data/Atomic.swift, Sources/BowEffects/Data/IO.swift, Sources/BowEffects/Data/Ref.swift, Sources/BowEffects/Typeclasses/Async.swift, Sources/BowEffects/Typeclasses/EffectComprehensions.swift, Sources/BowEffects/Typeclasses/MonadDefer.swift, Tests/BowEffectsLaws/AsyncLaws.swift, Tests/BowEffectsLaws/MonadDeferLaws.swift
Provide utilities to work with IO seamlessly.
- It renames some methods to have the same naming as in Arrow.
- Atomic is public.
- Some utilities to be used in monad comprehensions with effects.
=> IO Enhancements

Bow.xcodeproj/project.pbxproj, Sources/BowEffects/Foundation/FileManager.swift
Provide alternative methods in `FileManager` that allow us to perform file operations with side effects in a safe manner using IO.
=> Wrap side-effectful methods of FileManager in IO

Bow.xcodeproj/project.pbxproj, Sources/BowEffects/Typeclasses/Async.swift, Sources/BowEffects/Typeclasses/Bracket.swift, Sources/BowEffects/Typeclasses/Concurrent.swift, Sources/BowEffects/Typeclasses/ConcurrentEffect.swift, Sources/BowEffects/Typeclasses/Effect.swift, Sources/BowEffects/Typeclasses/EffectComprehensions.swift, Sources/BowEffects/Typeclasses/MonadDefer.swift, Sources/BowEffects/Typeclasses/UnsafeRun.swift
- Closes #410 
- Closes #411 
- Closes #412 
- Closes #413 
- Closes #414 
- Closes #415 
- Closes #416 
- Closes #417 
Add API documentation for the type class hierarchy for Effects.
=> Effects type classes API docs

Sources/BowEffects/Foundation/ConsoleIO.swift, Sources/BowEffects/Foundation/URLSession.swift
- Closes #408 
- Closes #409 
Add API docs for the extensions for Foundation in the Effects module.
=> Add API docs for Foundation extensions

Sources/BowRx/MaybeK.swift, Sources/BowRx/ObservableK.swift, Sources/BowRx/SingleK.swift
- Closes #418 
- Closes #419 
- Closes #420 
Add API docs for RxSwift extensions.
=> Add API docs for RxSwift extensions.

Sources/BowEffects/Data/Atomic.swift, Sources/BowEffects/Data/Ref.swift, Sources/BowEffects/Data/Resource.swift
- Closes #404 
- Closes #406 
- Closes #407 
Add API docs for utilities for IO
=> IO utils API docs

README.md, scripts/gen-docs.rb
Remove BrightFutures references from README and documentation process.
=> Remove BrightFutures references

Sources/BowEffects/Data/IO.swift
- Closes #405 
Adds IO API documentation.
=> Add IO API docs

contents/Documentation/Patterns.playground/Pages/Monad comprehensions.xcplaygroundpage/Contents.swift, contents/Documentation/Patterns.playground/contents.xcplayground
Add documentation page for Monad comprehensions.
=> Add Monad comprehensions doc page

Bow.podspec, BowEffects.podspec, BowEffectsGenerators.podspec, BowEffectsLaws.podspec, BowFree.podspec, BowFreeGenerators.podspec, BowGenerators.podspec, BowGeneric.podspec, BowLaws.podspec, BowOptics.podspec, BowOpticsLaws.podspec, BowRecursionSchemes.podspec, BowRx.podspec, BowRxGenerators.podspec, README.md, contents/Documentation/Effects.playground/Pages/Foundation extensions.xcplaygroundpage/Contents.swift, contents/Documentation/Effects.playground/Pages/Overview.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Data types.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/Pages/Higher Kinded Types.xcplaygroundpage/Contents.swift, contents/Documentation/FP concepts.playground/contents.xcplayground, contents/Documentation/Patterns.playground/Pages/Monad comprehensions.xcplaygroundpage/Contents.swift, contents/Documentation/Quick start.playground/Pages/Getting started.xcplaygroundpage/Contents.swift
- Update podspec versions to 0.6.0 in preparation for the new release.
- Fix minor issues in docs formatting.
=> Prepare release 0.6.0

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/Array.swift, Sources/Bow/Typeclasses/Foldable.swift, Tests/BowTests/Data/ArrayTests.swift
Add utility methods from Foldable and Traverse to Array.
Provide instances for Semigroup and Monoid for Array.
=> Add utilities to Array

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/Dictionary.swift, Sources/Bow/Data/DictionaryK.swift, Tests/BowGenerators/Data/DictionaryK+Gen.swift, Tests/BowTests/Data/ArrayTest.swift, Tests/BowTests/Data/DictionaryKTest.swift, Tests/BowTests/Data/DictionaryTest.swift
Add Semigroup and Monoid instances for Dictionary and DictionaryK
=> Add Semigroup and Monoid instances for Dictionary

Sources/Bow/Data/DictionaryK.swift, Tests/BowLaws/FoldableLaws.swift, Tests/BowTests/Data/DictionaryKTest.swift
Provide instances for Functor, FunctorFilter, Foldable and Traverse for Dictionary.
=> Provide instances for DictionaryK

Bow.xcodeproj/project.pbxproj, Sources/Bow/Arrow/Kleisli.swift, Sources/Bow/Data/Set.swift, Sources/Bow/Instances/NumberInstances.swift, Sources/BowEffects/Data/IO.swift, Tests/BowTests/Data/SetTest.swift
Add several utilities to different types.
=> Miscellaneous utilities

Bow.xcodeproj/project.pbxproj, Sources/Bow/Typeclasses/Decidable.swift
Resolves #453 
This PR adds the Decidable type class.
=> Add decidable type class

Bow.xcodeproj/project.pbxproj, contents/Documentation/Optics.playground/Pages/Writing your own optics.xcplaygroundpage/Contents.swift, contents/Documentation/Quick start.playground/Pages/Resources.xcplaygroundpage/Contents.swift
This PR adds a repository, a talk and a blog post, and fixes a couple of issues in the project.
=> Add resources

Sources/BowOptics/DSL/At+Optics.swift, Sources/BowOptics/DSL/Each+Optics.swift, Sources/BowOptics/DSL/Index+Optics.swift, Sources/BowOptics/Iso.swift, Sources/BowOptics/Lens.swift, Sources/BowOptics/Optional.swift, Sources/BowOptics/Prism.swift, Sources/BowOptics/Setter.swift, Sources/BowOptics/Traversal.swift
Combine two lenses with the same source but different focus.
=> Utilities for lens

contents/Documentation/Effects.playground/Pages/Retrying and repeating effects.xcplaygroundpage/Contents.swift, contents/Documentation/Effects.playground/contents.xcplayground, contents/Documentation/Podfile.lock
Provide documentation on scheduling policies to retry and repeat effects.
=> Documentation for retrial and repeat effects

Sources/Bow/Data/Day.swift, Tests/BowGenerators/Data/Day+Gen.swift, Tests/BowTests/Data/DayTest.swift
- Closes #236 
Provide correct instances for Day and add some missing functions.
Implementation is based on a port from the [Haskell version](https://hackage.haskell.org/package/contravariant-0.6.1/docs/src/Data-Functor-Day.html). More info about Day can be found in [this blog post](https://blog.functorial.com/posts/2016-08-08-Comonad-And-Day-Convolution.html).
Laws for the instances are checked.
=> Day Convolution

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/Zipper.swift, Tests/BowGenerators/Data/Zipper+Gen.swift, Tests/BowTests/Data/ZipperTest.swift
Add Zipper data type with instances for `Functor` and `Comonad`.
=> Add Zipper

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/Endo.swift, Tests/BowGenerators/Data/Endo+Gen.swift, Tests/BowTests/Data/EndoTest.swift
For an explanation on why the `Endo` Monoid is useful, check this awesome post: https://bkase.dev/posts/reducers-are-monoids
Huge thanks to @truizlop for the help and patience! 😉 🙌
=> Implement Endo Monoid 🦅

nef-compile.yml
Add a GitHub workflow to compile docs using nef.
All commands are based on the current Travis implementation.
=> Add nef compile action

.travis.yml, Bow.xcodeproj/project.pbxproj, Sources/Bow/Transformers/StateT.swift, Sources/BowEffects/Typeclasses/MonadDefer.swift, Sources/BowOptics/Auto/AutoPrism.swift, Sources/BowOptics/Extensions/StateT+Optics.swift, Sources/BowOptics/Fold.swift, Sources/BowOptics/Optional.swift, Sources/BowOptics/Prism.swift, Sources/BowOptics/Traversal.swift
This PR adds some improvements to the ergonomics of the optics module, together with some convenience methods to work with `State` + optics.
=> Ergonomics improvements

.github/workflows/deploy-docs.yml
Migrate docs generation from Travis to GitHub Actions.
=> Create workflow to deploy docs

.github/workflows/deploy-docs.yml
=> Update deploy action to v3

.github/workflows/deploy-docs.yml
Update deploy key for creating the new GitHub pages for the Bow site
=> Update secrets for deploy gh pages

.github/workflows/deploy-docs.yml
* Update deploy action settings
=> Update deploy action settings

.github/workflows/deploy-docs.yml
* Fix deployment directory and token
=> Fix deployment directory and token

.github/workflows/deploy-docs.yml
* Set correct token option name :man_facepalming:
=> Set correct token option name

.github/workflows/nef-compile.yml, .github/workflows/swift.yml, scripts/push.sh
Run compilation and tests, as well as documentation compilation, only on PR.
=> Fine tune workflows

Sources/Bow/Transformers/EnvT.swift, Sources/Bow/Transformers/StoreT.swift, Sources/Bow/Transformers/TracedT.swift
- Closes #530 
- Closes #531 
- Closes #532
Add API Reference for the Comonad Transformers.
=> Comonad Transformers API Reference

Sources/Bow/Data/Trampoline.swift
- Closes #542 
Add API documentation for Trampoline.
=> Document Trampoline API

Sources/Bow/Data/Co.swift
- Closes #534 
Add API Reference for CoT.
=> Document CoT API

Sources/Bow/Data/Co.swift, Sources/Bow/Data/CoSum.swift, Sources/Bow/Data/Sum.swift
- Closes #541 
- Closes #535  
Add API Reference for Sum and CoSum.
=> Document Sum & CoSum API

Sources/Bow/Data/Action.swift, Sources/Bow/Data/Moore.swift
- Closes #538 
- Closes #533 
Add API Reference for Moore and Action.
=> Document Moore & Action API

Sources/Bow/Data/Puller.swift, Sources/Bow/Data/Zipper.swift
- Closes #547 
- Closes #540 
Add API Reference for Zipper and Puller.
=> Document Zipper-Puller API

Documentation.app/Contents/MacOS/FP concepts.playground/Pages/Data types.xcplaygroundpage/Contents.swift
Add recently added data types to its documentation page.
=> Add missing data types to documentation page

Sources/Bow/Data/Pairing.swift
- Closes #539 
Add API Reference for Pairing.
=> Document Pairing API

Sources/Bow/Data/Day.swift
- Closes #536 
Add API Reference for Day.
=> Document Day API

Documentation.app/Contents/MacOS/Documentation.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme, Documentation.app/Contents/MacOS/Patterns.playground/Pages/Tail recursion.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Patterns.playground/contents.xcplayground
Provide documentation and examples on how to transform a recursive function into a tail recursive one, and use Trampoline to avoid stack overflow issues.
=> Add documentation page for tail recursion and trampolining

Documentation.app/Contents/MacOS/FP concepts.playground/Pages/Higher Kinded Types.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Quick start.playground/Pages/Modules.xcplaygroundpage/Contents.swift
Remove some old references to BrightFutures in the documentation.
=> Remove references to BrightFutures in documentation

scripts/gen-docs.rb
Closes #128
Fix Dash URL for API References
=> Fix dash url

Sources/Bow/Arrow/Kleisli.swift, Sources/Bow/Transformers/EitherT.swift, Sources/Bow/Transformers/OptionT.swift, Sources/Bow/Transformers/StateT.swift, Sources/Bow/Transformers/WriterT.swift, Tests/BowEffectsTests/EnvIOTest.swift, Tests/BowTests/Arrow/KleisliTest.swift, Tests/BowTests/Transformers/OptionTTest.swift, Tests/BowTests/Transformers/StateTTest.swift, Tests/BowTests/Transformers/WriterTTest.swift
Add missing instances for type classes of Monad Transformers and clean up code to make it easier to read and maintain.
=> Monad Transformer instances

Sources/Bow/Transformers/EnvT.swift, Sources/Bow/Transformers/StoreT.swift, Sources/Bow/Transformers/TracedT.swift, Tests/BowTests/Transformers/EnvTTest.swift, Tests/BowTests/Transformers/StoreTTest.swift, Tests/BowTests/Transformers/TracedTTest.swift
This PR adds instances for Comonad Transformers that can be derived from the Comonad stack.
=> Comonad Transformer instances

Documentation.app/Contents/MacOS/Patterns.playground/Pages/State-based computations.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Patterns.playground/contents.xcplayground
Create documentation page for State-based computations.
=> State-based computations documentation page

Documentation.app/Contents/MacOS/Patterns.playground/Pages/State-based computations.xcplaygroundpage/Contents.swift
The recently merged PR with documentation about State (#582) has some rendering/formatting issues with the `nef:begin:hidden` blocks. This PR reorders those blocks to eliminate the issues.
=> Formatting changes

Sources/Bow/Arrow/Kleisli.swift
Improve the ergonomics of accessing the environment for a Kleisli function.
=> Add access and accessM to Kleisli

Documentation.app/Contents/MacOS/Dependency management.playground/Pages/Constructor-based dependency injection.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Dependency management.playground/Pages/Dependency management Overview.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Dependency management.playground/Pages/Partial application.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Dependency management.playground/Pages/Reader.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Dependency management.playground/Pages/Side-effectful dependency management.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Documentation.xcworkspace/contents.xcworkspacedata, Documentation.app/Contents/MacOS/Podfile, Documentation.app/Contents/MacOS/Podfile.lock, Documentation.app/Contents/MacOS/Testing.playground/Pages/Testing Overview.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Testing.playground/Pages/Testing side effectful code.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Testing.playground/Pages/Testing type class instances.xcplaygroundpage/Contents.swift, Documentation.app/Contents/MacOS/Testing.playground/contents.xcplayground, Documentation.app/Contents/MacOS/Testing.playground/playground.xcworkspace/contents.xcworkspacedata
Add pages with documentation about testing:
- Overview
- Testing type class laws
- Testing side effectful code
=> Testing series

.github/workflows/deploy-docs.yml, .github/workflows/nef-compile.yml, .github/workflows/swift.yml, Package.swift
Add workflow to run tests in Linux. It allows us to keep Linux compatibility verified before to merge any PR.
=> CI: run tests in linux

Sources/BowOptics/Prism.swift
#603 
There is a way of creating a Prism with embed and extract, but not a way of retrieving these properties.
=> Add extract and embed properties to Prism

scripts/gen-docs.rb
Updates the default version that is built when creating docs.
=> Update default documentation version

Documentation.app/Contents/MacOS/Podfile.lock, README.md
A section in the README included outdated documentation about how to resolve dependencies and open documentation. This PR updates it.
=> Update instructions on how to contribute to docs

Sources/Bow/Typeclasses/MonadComprehensions/MonadComprenhensions.swift, Tests/BowLaws/MonadLaws.swift
=> Add bindings overload based on FunctionBuilders

Sources/Bow/Data/Tree.swift, Tests/BowTests/Data/TreeTest.swift
Just some docs, renaming and make properties public.
=> Some tweaks to Tree

Sources/Bow/Data/ArrayK.swift, Sources/Bow/Typeclasses/Foldable.swift, Tests/BowTests/Data/ArrayKTest.swift
=> Add asArray method to Foldable

scripts/gen-docs.rb
This PR simplify/compact how to deploy the docs: removes duplicate code, ...
=> Compact logic to deploy docs

Bow.xcodeproj/project.pbxproj, Sources/Bow/Data/Yoneda.swift, Tests/BowGenerators/Data/Yoneda+Gen.swift, Tests/BowTests/Data/YonedaTest.swift
=> Move Yoneda to Bow module

Bow.xcodeproj/project.pbxproj, Sources/Bow/Transformers/EitherT.swift, Sources/Bow/Transformers/EnvT.swift, Sources/Bow/Transformers/OptionT.swift, Sources/Bow/Transformers/StateT.swift, Sources/Bow/Transformers/StoreT.swift, Sources/Bow/Transformers/TracedT.swift, Sources/Bow/Transformers/WriterT.swift, Sources/Bow/Typeclasses/ComonadTrans.swift, Sources/Bow/Typeclasses/MonadTrans.swift, Tests/BowGenerators/Typeclasses/ArbitraryK.swift, Tests/BowLaws/ComonadTransLaws.swift, Tests/BowLaws/MonadTransLaws.swift, Tests/BowTests/Transformers/EitherTTest.swift, Tests/BowTests/Transformers/EnvTTest.swift, Tests/BowTests/Transformers/OptionTTest.swift, Tests/BowTests/Transformers/StateTTest.swift, Tests/BowTests/Transformers/StoreTTest.swift, Tests/BowTests/Transformers/TracedTTest.swift, Tests/BowTests/Transformers/WriterTTest.swift
Be able to test Monad and Comonad transformers implementation.
I added MonadTrans typeclass with its laws. I added ComonadTrans typeclass with its laws. Instances for each transformer are also included.
=> Monad trans

Bow.xcodeproj/project.pbxproj, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Effects-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Effects.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Free-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Free.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Generic.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Optics.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-OpticsLaws.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-RecursionSchemes.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Rx-Generators.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow-Rx.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/Bow.xcscheme, Bow.xcodeproj/xcshareddata/xcschemes/BowAllTests.xcscheme, Sources/Bow/Data/Result.swift
Enhance Result with a more complete API, containing Functor, Applicative, Monad and ApplicativeError functions.
=> Extend Result API
