bow-swift/bow

.gitignore
Bow.xcodeproj/project.pbxproj
Sources/Bow/Typeclasses/Show.swift
Tests/BowTests/Data/ConstTest.swift
Tests/BowTests/Data/EitherTest.swift
Tests/BowTests/Data/IdTest.swift
Tests/BowTests/Data/IorTest.swift
Tests/BowTests/Data/MaybeTest.swift
Tests/BowTests/Data/NonEmptyListTest.swift
Tests/BowTests/Data/TryTest.swift
Tests/BowTests/Data/ValidatedTest.swift
Tests/BowTests/Typeclasses/ShowLaws.swift

The PR adds `Show` typeclass and its test laws. It provides a default instance of `Show` for all those classes that implement `CustomStringConvertible` in Swift. Currently, the following data classes provide such implementation in Bow:
- Const
- Either
- Id
- Ior
- Maybe
- NonEmptyList
- Try
- Validated
All of them have been tested. Additionally, all Swift plain types implement `CustomStringConvertible` and as such provide a `Show` instance.

Add Show typeclass

---

Sources/Bow/Optics/Typeclasses/At.swift
Sources/Bow/Optics/Typeclasses/Each.swift
Sources/Bow/Optics/Typeclasses/FilterIndex.swift
Sources/Bow/Optics/Typeclasses/Index.swift

This PR extends the existing typeclasses for optics (namely `At`, `Each`, `Index` and `FilterIndex`) with static methods to create implementations for them, from `Iso` and `Traverse`.

Extend optics typeclasses

---

Sources/Bow/Data/Const.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/ListK.swift
Sources/Bow/Data/Maybe.swift
Sources/Bow/Data/NonEmptyList.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Validated.swift

This PR adds conformance to Equatable to the following data types:
- `Const`
- `Either`
- `Id`
- `Ior`
- `ListK`
- `Maybe`
- `NonEmptyList`
- `Try`
- `Validated`

Make data types conform to Equatable

---

Sources/Bow/Data/Const.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/ListK.swift
Sources/Bow/Data/Maybe.swift
Sources/Bow/Data/NonEmptyList.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Validated.swift

This PR adds conformance to `CustomDebugStringConvertible` to the following data types:
- `Const`
- `Either`
- `Id`
- `Ior`
- `ListK`
- `Maybe`
- `NonEmptyList`
- `Try`
- `Validated`
Conformance to this protocol provides an easier understanding of the contents of a data type when debugging it.

Conformance to CustomDebugStringConvertible

---

Bow.xcodeproj/project.pbxproj

Fixes #38. `BoolInstances` was only included in the main target and caused other targets not to compile.

Add file to all targets

---

Bow.podspec
scripts/push.sh

Until we fix https://github.com/arrow-kt/bow/issues/41 we should pass the flag --allow-warnings to the pod trunk push command for this to work

Fix release process

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/Day.swift
Sources/Bow/Data/Moore.swift
Sources/Bow/Data/Store.swift
Sources/Bow/Data/Sum.swift
Tests/BowTests/Data/DayTest.swift
Tests/BowTests/Data/MooreTest.swift
Tests/BowTests/Data/StoreTest.swift
Tests/BowTests/Data/SumTest.swift

This PR adds several data types described in the paper [Declarative UIs are the Future - and the Future is Comonadic!](https://functorial.com/the-future-is-comonadic/main.pdf) and implemented as in [this PR in Arrow](https://github.com/arrow-kt/arrow/pull/1020). The included data types are:
- Store
- Moore
- Sum
- Day
The only missing things with respect to the Arrow version are the `lazy` versions of methods in `Day`, and the applicative instances. I had several problems with types and generics and couldn't implement them in a safe way. I'd probably need to revisit this in the future.

Comonadic UIs data types

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Syntax/Curry.swift
Sources/Bow/Syntax/Predef.swift
Tests/BowTests/Typeclasses/ApplicativeErrorLaws.swift
Tests/BowTests/Typeclasses/ApplicativeLaws.swift
Tests/BowTests/Typeclasses/ComonadLaws.swift
Tests/BowTests/Typeclasses/FunctorLaws.swift
Tests/BowTests/Typeclasses/MonadErrorLaws.swift
Tests/BowTests/Typeclasses/MonadFilterLaws.swift
Tests/BowTests/Typeclasses/MonadLaws.swift

Previous version used constant functions in property-based tests for typeclasses laws. This PR replaces those constant functions (where possible) by `ArrowOf<A, B>`, provided by SwiftCheck, which generates functions with signature `(A) -> B`, making the tests of properties more robust.

Improve testing for typeclasses laws

---

BowBrightFutures.podspec
BowEffects.podspec
BowFree.podspec
BowGeneric.podspec
BowOptics.podspec
BowRecursionSchemes.podspec
BowResult.podspec
BowRx.podspec

Podspecs were missing internal dependencies, mainly to the core Bow module. This PR adds them and prepares release 0.2.0.
These podspecs need to be linted with Cocoapods 1.6.0-beta2 since there is a bug in previous versions which was throwing a false negative error when building the library for macOS. Probably this version needs to be used for release as well.

Update podspecs to have the proper dependencies listed

---

BowRx.podspec
Cartfile
Cartfile.private

Carthage is not able to resolve transitive dependencies because they were in the private file. Also, Rx dependencies need to be in version 4.4 in order to work with Swift 4.2.

Fix broken dependencies

---

Sources/Bow/Arrow/KleisliOperator.swift
Sources/Bow/Data/FlatmapOperator.swift
Tests/BowLaws/FunctorFilterLaws.swift

Operators >>= (flatMap) and >=> (Kleisli composition) are not generic enough, and often controversial. For the sake of readability and ease of understanding of the code, these operators are being deprecated.

Deprecate operators

---

Sources/Bow/Arrow/Function0.swift
Sources/Bow/Arrow/Function1.swift
Sources/Bow/Arrow/Kleisli.swift
Sources/Bow/Data/Const.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Eval.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/ListK.swift
Sources/Bow/Data/MapK.swift
Sources/Bow/Data/NonEmptyList.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Data/Reader.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Validated.swift
Sources/Bow/Transformers/EitherT.swift
Sources/Bow/Transformers/OptionT.swift
Sources/Bow/Transformers/StateT.swift
Sources/Bow/Transformers/WriterT.swift
Sources/Bow/Typeclasses/Applicative.swift
Sources/BowBrightFutures/FutureK.swift
Sources/BowEffects/IO.swift
Sources/BowFree/Free.swift
Sources/BowRx/MaybeK.swift
Sources/BowRx/ObservableK.swift
Sources/BowRx/SingleK.swift
Tests/BowLaws/AlternativeLaws.swift
Tests/BowLaws/ApplicativeLaws.swift

As suggested in #77, for a nicer usage of `ap`, the wrapped function should be on the left hand side of `ap`, allowing for a better syntax call. This PR provides this change in every data type supporting `ap`, in the `Applicative` typeclass (swapping arguments for a better curried version) and in all instances of such typeclass.

Refactor ap method in Applicative

---

Sources/Bow/Data/Const.swift
Sources/Bow/Data/Coproduct.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/ListK.swift
Sources/Bow/Data/MapK.swift
Sources/Bow/Data/NonEmptyList.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Data/SetK.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Validated.swift
Sources/Bow/Typeclasses/Composed/ComposedFoldable.swift
Sources/Bow/Typeclasses/Foldable.swift
Sources/Bow/Typeclasses/MonadCombine.swift
Sources/Bow/Typeclasses/NonEmptyReducible.swift
Sources/BowRx/MaybeK.swift
Sources/BowRx/ObservableK.swift
Tests/BowLaws/FoldableLaws.swift

`foldL` and `foldR` are replaced by better names `foldLeft` and `foldRight`.

Rename foldL and foldR

---

docs/_includes/_google-tag-manager.html

* Simple fix to set the Google Analytics id parameter to be read from config, as it was incorrectly set as a hardcoded value.

Read GA id from config

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Syntax/BooleanFunctions.swift
Sources/Bow/Syntax/Curry.swift
Sources/Bow/Syntax/HigherKinds.swift
Sources/Bow/Syntax/Memoization.swift
Sources/Bow/Syntax/PartialApplication.swift
Sources/Bow/Syntax/Predef.swift
Sources/Bow/Syntax/Reverse.swift
Sources/Bow/Syntax/Typeclass.swift

Closes #101.
Closes #102.
Closes #103.
Closes #104.
Closes #106.
Closes #107.
Closes #108.
Closes #109.
Adds API documentation to:
- Boolean functions
- Curry
- Memoization
- Reverse
- Predefs
- PartialApplication
- Typeclass
- Higher Kinded Types

Add API docs to Syntax group

---

Sources/Bow/Data/ArrayK.swift
Sources/Bow/Data/Const.swift
Sources/Bow/Data/Coproduct.swift
Sources/Bow/Data/Day.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Eval.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/Moore.swift
Sources/Bow/Data/NonEmptyArray.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Data/SetK.swift
Sources/Bow/Data/State.swift
Sources/Bow/Data/Store.swift
Sources/Bow/Data/Sum.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Tuple.swift
Sources/Bow/Data/Validated.swift
Sources/Bow/Instances/BoolInstances.swift
Sources/Bow/Instances/NumberInstances.swift
Sources/Bow/Instances/StringInstances.swift
Sources/Bow/Typeclasses/Foldable.swift
Tests/BowTests/Data/SetKTest.swift
Tests/BowTests/Transformers/WriterTTest.swift

- Improve modularity of instances of typeclasses for data types.
- Improve readability of generated documentation
Instances of typeclasses for data types are now defined inside its class implementation; for instance, previous class `ArrayKApplicative` was defined in a global scope. Now, it is defined in the `ArrayK` scope and renamed to `ApplicativeInstance`; therefore, it's full name is `ArrayK<A>.ApplicativeInstance`.

Regroup instances under data types

---

Sources/Bow/Arrow/Function0.swift
Sources/Bow/Arrow/Kleisli.swift
Sources/Bow/Data/ArrayK.swift
Sources/Bow/Data/Const.swift
Sources/Bow/Data/Coproduct.swift
Sources/Bow/Data/Day.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/Eval.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/NonEmptyArray.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Data/SetK.swift
Sources/Bow/Data/Sum.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Tuple.swift
Sources/Bow/Data/Validated.swift
Sources/Bow/Transformers/EitherT.swift
Sources/Bow/Transformers/OptionT.swift
Sources/Bow/Transformers/StateT.swift
Sources/Bow/Transformers/WriterT.swift
Sources/BowEffects/IO.swift
Sources/BowFree/Cofree.swift
Sources/BowFree/Coyoneda.swift
Sources/BowFree/Free.swift
Sources/BowFree/Yoneda.swift

To have a single way to construct and demand for instances for a given typeclass instance for a data type.
This PR removes the `public` visibility modifier from the `init` methods in some instances of typeclasses for data types that allowed users to build instances directly, instead of using the designated `static` methods in the corresponding data types. Since this was only possible in a few cases, the decision is to remove the accessibility to such initializers and force the usage of `static` methods to retrieve instances. An example: consider that an instance of `Eq` is needed for `Option<Int>`. Instead of initializing it manually:
```swift
let eq = Option<Int>.EqInstance(Int.EqInstance())
```
The correct way is:
```swift
let eq = Option<Int>.eq(Int.eq)
```

Remove public visibility of initializers in typeclass instances

---

Sources/Bow/Syntax/HigherKinds.swift
Sources/Bow/Typeclasses/Monad.swift
Sources/BowEffects/Typeclasses/Async.swift
Sources/BowEffects/Typeclasses/ConcurrentEffect.swift
Sources/BowEffects/Typeclasses/Effect.swift
Sources/BowEffects/Typeclasses/MonadDefer.swift
Sources/BowRecursionSchemes/Typeclasses/Corecursive.swift
Sources/BowRecursionSchemes/Typeclasses/Recursive.swift

Jazzy uses `// MARK:` as delimiters for sections in the docs. This PR adds some missing ones in order to have better sectioned docs for `Kind`.

Add MARK to docs section

---

Sources/Bow/Data/Either.swift
Sources/Bow/Data/Id.swift

Use the triple slash syntax (`///`) autogenerated by Xcode in the docs for `Either` to keep consistency across the codebase.

Reformat Either docs

---

Sources/Bow/Data/Option.swift

Use the triple slash syntax (`///`) autogenerated by Xcode in the docs for `Option` to keep consistency across the codebase.

Reformat Option docs

---

Sources/Bow/Typeclasses/FunctorFilter.swift
Sources/Bow/Typeclasses/MonadFilter.swift
Sources/Bow/Typeclasses/TraverseFilter.swift

- Closes #165.
- Closes #166.
- Closes #167.
Add API docs for FunctorFilter, MonadFilter and TraverseFilter.

Add docs for FunctorFilter, MonadFilter and TraverseFilter

---

Sources/Bow/Typeclasses/Applicative.swift
Sources/Bow/Typeclasses/Functor.swift
Sources/Bow/Typeclasses/Invariant.swift
Sources/Bow/Typeclasses/Monad.swift
Sources/BowRecursionSchemes/Recursion.swift

- Closes #147.
- Closes #148.
- Closes #149.
- Closes #150.
Add API docs for `Invariant`, `Functor`, `Applicative` and `Monad`.

API docs for Invariant, Functor, Applicative and Monad

---

Sources/Bow/Typeclasses/MonadCombine.swift
Sources/Bow/Typeclasses/MonadReader.swift
Sources/Bow/Typeclasses/MonadState.swift
Sources/Bow/Typeclasses/MonadWriter.swift

- Closes #175.
- Closes #176.
- Closes #177.
- Closes #178.
Add API docs for MonadCombine, MonadReader, MonadState and MonadWriter.

Add docs for MonadCombine, MonadReader, MonadState and MonadWriter

---

Sources/Bow/Arrow/FunctionK.swift
Sources/Bow/Data/Coproduct.swift
Sources/BowFree/Cofree.swift
Sources/BowFree/Free.swift
Tests/BowFreeTests/FreeTest.swift

- Closes #173.
- Add API docs for FunctionK.
- Changes `FunctionK` from a protocol to an abstract class.
Changing `FunctionK` from protocol to class eases the readability of the code and makes it easier to implement for clients. Also, composition of FunctionK is introduced.

Add docs for FunctionK

---

Sources/Bow/Typeclasses/Alternative.swift
Sources/Bow/Typeclasses/MonoidK.swift
Sources/Bow/Typeclasses/SemigroupK.swift

- Closes #152.
- Closes #153.
- Closes #154.
Adds API docs for `SemigroupK`, `MonoidK` and `Alternative`.

API docs for SemigroupK, MonoidK and Alternative

---

Sources/Bow/Syntax/Predef.swift
Sources/Bow/Typeclasses/Selective.swift

Issue: #247 
Provide a lazy implementation of `constant`.
@autoclosure is a syntax sugar to be able to use a function as a parameter without wrapping it between `{}`, however, the signature of the function will specify a function as the parameter, because of this, some usages have been adapted to the new syntax.
Tests not affected

Uses @autoclosure in constant functions

---

Sources/Bow/Arrow/Function0.swift
Sources/Bow/Arrow/Function1.swift
Tests/BowTests/Arrow/Function1Test.swift

- Closes #223 
- Closes #229 
Update Function1 with missing things respect to the Arrow version. Instances for `Category`, `Contravariant` and `Profunctor` are not possible to write at the moment and therefore are left out of this PR.

Add missing functions and instances to Function1

---

Sources/Bow/Data/Try.swift
Tests/BowTests/Data/TryTest.swift

- Closes #225 
- Closes #233 
Add missing functionality to Try respect to the Arrow version.
Some missing functions and instances have been added. Some notes:
- Instance to `Hashable` has not been added. All instances of `Hashable` should be added separately in a single PR.
- `rescue` is deprecated and replaced by `handleErrorWith` from `ApplicativeError`, which is already present.
- `flatten` is already present from `Monad`.
- `exists` is already present from `Foldable`.
Laws for Semigroup and Monoid are tested.

Add missing functions to Try

---

docs/_includes/_doc-wrapper.html

* With the current way of generating documentation through `nef`, the edit button is deprecated.

Remove edit button from doc pages

---

Sources/BowBrightFutures/FutureK.swift
Sources/BowEffects/IO.swift
Sources/BowEffects/Typeclasses/Async.swift
Sources/BowRx/MaybeK.swift
Sources/BowRx/ObservableK.swift
Sources/BowRx/SingleK.swift

let a user call the callback defined in the runAsync PR, previous to this PR, the compiler would complain about the callback being non-escaping (Closure use of non-escaping parameter 'callback' may allow it to escape)
add @escaping to the runAsync method in IO.swift and Async.swift
if you want me to add tests, where do you want me to put those ? :)

add @escaping keyword to runAsync<A> methods of Async and IO

---

Sources/Bow/Data/NonEmptyArray.swift
Sources/Bow/Data/Result.swift
contents/Documentation/Quick start.playground/Pages/Resources.xcplaygroundpage/Contents.swift
contents/Documentation/Quick start.playground/contents.xcplayground

- Provide API docs for extensions to convert from/to Result in Swift 5.
- Fix typo in NonEmptyArray.
- Add presentation about Error management.

Result API docs and minor fixes

---

contents/Home.md
docs/index.md

This fix the permalink for Jekyll in `main page` - That way the files/path generated in the end could be navigated through `bow-swift.io/docs` and `bow-swift.io/docs/`. Without it, a path not ending in a slash will give you a 404 😵

fix permalink for main page

---

Sources/Bow/Arrow/Function0.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/EitherK.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Transformers/EitherT.swift
Sources/Bow/Transformers/OptionT.swift
Sources/Bow/Transformers/WriterT.swift
Tests/BowTests/Arrow/Function0Test.swift
Tests/BowTests/Data/EitherKTest.swift
Tests/BowTests/Data/EitherTest.swift
Tests/BowTests/Data/IdTest.swift
Tests/BowTests/Data/OptionTest.swift
Tests/BowTests/Transformers/EitherTTest.swift
Tests/BowTests/Transformers/OptionTTest.swift
Tests/BowTests/Transformers/WriterTTest.swift

- Closes #228
- Closes #228
- Closes #231
- Closes #249 
- Closes #250
- Closes #255
- Closes #261
- Closes #265
Implement conformances to some type classes for several types in the core module that didn't have them respect to their Arrow counterpart.

Add missing instances for some types

---

Bow.xcodeproj/project.pbxproj
Sources/BowOptics/Auto/AutoGetter.swift
Sources/BowOptics/Auto/AutoSetter.swift

Following the work done in #341, three new optics are automatically derived using the same techniques described in such PR. The three new optics that we are able to derive are `Getter`, `Setter` and `BoundSetter`. They can be seen as specializations of the work done for `Lens`.
Given the following type:
```swift
struct Person {
var name: String
var age: Int
}
```
We can get `Getter` and `Setter` as:
```swift
let nameGetter = Person.getter(for: \.name)
let ageSetter = Person.setter(for: \.age)
```
In the case of `BoundSetter`, we need to provide a specific value:
```swift
let person = Person(name: "Tomás", age: 32)
let ageBoundSetter = Person.boundSetter(for: \.age, onValue: person)
// Or alternatively
let ageBoundSetter2 = person.boundSetter(for: \.age)
```

Automatic derivation of Getter, Setter and BoundSetter

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/ArrayK.swift
Sources/BowOptics/Instances/ArrayKOpticsInstances.swift
Sources/BowOptics/Instances/ArrayOpticsInstances.swift
Sources/BowOptics/Instances/ConstOpticsInstances.swift
Sources/BowOptics/Instances/EitherKOpticsInstances.swift
Sources/BowOptics/Instances/EitherOpticsInstances.swift
Sources/BowOptics/Instances/IdOpticsInstances.swift
Sources/BowOptics/Instances/IorOpticsInstances.swift
Sources/BowOptics/Instances/NonEmptyArrayOpticsInstances.swift
Sources/BowOptics/Instances/OptionOpticsInstances.swift
Sources/BowOptics/Instances/StringOpticsInstances.swift
Sources/BowOptics/Instances/TryOpticsInstances.swift
Sources/BowOptics/Instances/ValidatedOpticsInstances.swift
Sources/BowOptics/STD/ArrayK+Optics.swift
Sources/BowOptics/STD/Either+Optics.swift
Sources/BowOptics/STD/Ior+Optics.swift
Sources/BowOptics/STD/Result+Optics.swift
Sources/BowOptics/STD/Validated+Optics.swift
Sources/BowOptics/Typeclasses/At.swift
Sources/BowOptics/Typeclasses/Cons.swift
Sources/BowOptics/Typeclasses/Each.swift
Sources/BowOptics/Typeclasses/FilterIndex.swift
Sources/BowOptics/Typeclasses/Index.swift
Sources/BowOptics/Typeclasses/Snoc.swift

- Closes #311 
- Closes #306
- Closes #309
Adds several missing instances for optics type classes for some of the core types. In addition, this PR adds traversals and folds to types in the core package that support `Traverse` and `Foldable`. Finally, prisms to access each case in `Either`,`Ior`, `Validated` and `Result` have been added.

Missing optics instances

---

Bow.xcodeproj/project.pbxproj
Sources/BowOptics/Auto/AutoFold.swift
Sources/BowOptics/Auto/AutoTraversal.swift

Following the work done in #341 and #350, this PR adds automatic derivation of `Fold` and `Traverse` for those fields where it makes sense to have such optics. Both can be derived for `Array` and `ArrayK`, but not limited to that. `Fold` can be derived for any field that has a `Foldable` instance, and `Traversal` can be derived for any field that has a `Traverse` instance.
Thus, considering the following data type:
```swift
struct Foo {
var array: [Int]
var arrayK: ArrayK<String>
var nea: NEA<Double>
}
```
We can derive `Fold`:
```swift
extension Foo: AutoFold {}
let arrayFold = Foo.fold(for: \.array)
let arrayKFold = Foo.fold(for: \.arrayK)
let neaFold = Foo.fold(for: \.nea)
```
Similarly, we can derive `Traversal`:
```swift 
extension Foo: AutoTraversal {}
let arrayTraversal = …
```

Automatic derivation of Fold and Traversal

---

Sources/BowOptics/Instances/ArrayKOpticsInstances.swift
Sources/BowOptics/Instances/ArrayOpticsInstances.swift
Sources/BowOptics/Instances/ConstOpticsInstances.swift
Sources/BowOptics/Instances/EitherKOpticsInstances.swift
Sources/BowOptics/Instances/EitherOpticsInstances.swift
Sources/BowOptics/Instances/IdOpticsInstances.swift
Sources/BowOptics/Instances/IorOpticsInstances.swift
Sources/BowOptics/Instances/NonEmptyArrayOpticsInstances.swift
Sources/BowOptics/Instances/OptionOpticsInstances.swift
Sources/BowOptics/Instances/StringOpticsInstances.swift
Sources/BowOptics/Instances/TryOpticsInstances.swift
Sources/BowOptics/Instances/ValidatedOpticsInstances.swift

- Closes #360 
Add API reference for the instances and default optics for some types in the core module.

Add API reference for optics instances

---

Sources/BowOptics/STD/ArrayK+Optics.swift
Sources/BowOptics/STD/Either+Optics.swift
Sources/BowOptics/STD/Id+Optics.swift
Sources/BowOptics/STD/Ior+Optics.swift
Sources/BowOptics/STD/NonEmptyArray+Optics.swift
Sources/BowOptics/STD/Option+Optics.swift
Sources/BowOptics/STD/Result+Optics.swift
Sources/BowOptics/STD/String+Optics.swift
Sources/BowOptics/STD/Try+Optics.swift
Sources/BowOptics/STD/Validated+Optics.swift

- Closes #362.
This PR adds documentation to the API of optics provided for the core data types in Bow.

Add API reference for utility optics for core data types

---

Bow.xcodeproj/project.pbxproj
Sources/BowEffects/Data/Atomic.swift
Sources/BowEffects/Data/Internal/CancelablePromise.swift
Sources/BowEffects/Data/Internal/Dictionary+Extensions.swift
Sources/BowEffects/Data/Internal/Token.swift
Sources/BowEffects/Data/Internal/UncancelablePromise.swift
Sources/BowEffects/Data/Internal/UnsafePromise.swift
Sources/BowEffects/Data/Promise.swift
Sources/BowEffects/Data/Ref.swift

- Closes #268 
Add `Promise` concurrency primitive. There are two concrete implementations: `CancelablePromise` and `UncancelablePromise`. There is an unsafe implementation `UnsafePromise`. A protocol `PromiseError` to describe errors that can be thrown from a `Promise` is also included.

Add Promise

---

Sources/BowGeneric/Coproduct10.swift
Sources/BowGeneric/Coproduct2.swift
Sources/BowGeneric/Coproduct3.swift
Sources/BowGeneric/Coproduct4.swift
Sources/BowGeneric/Coproduct5.swift
Sources/BowGeneric/Coproduct6.swift
Sources/BowGeneric/Coproduct7.swift
Sources/BowGeneric/Coproduct8.swift
Sources/BowGeneric/Coproduct9.swift

- Closes #387.
Add API documentation for all Coproduct data types, from 2 to 10.

Add API reference for Coproducts

---

contents/Documentation/Documentation.xcworkspace/contents.xcworkspacedata
contents/Documentation/Optics.playground/Pages/Automatic derivation.xcplaygroundpage/Contents.swift
contents/Documentation/Optics.playground/Pages/Composition.xcplaygroundpage/Contents.swift
contents/Documentation/Optics.playground/Pages/Overview.xcplaygroundpage/Contents.swift
contents/Documentation/Optics.playground/Pages/Writing your own optics.xcplaygroundpage/Contents.swift
contents/Documentation/Optics.playground/contents.xcplayground
contents/Documentation/Optics.playground/playground.xcworkspace/contents.xcworkspacedata

Add documentation about how to use optics. This PR includes 4 pages for the microsite:
- **Overview**: contains a description of the optics module and reference tables with the optics and type classes provided in the module.
- **Writing your own optics**: contains an explanation with a running example about how to write each of the provided optics.
- **Automatic derivation**: presents the same example as above, but showing how the library has mechanisms to derive automatically all optics.
- **Composition**: contains a table describing all possible compositions between different optics, and an example to apply all the techniques present in the module.

Documentation for Optics

---

.travis.yml
Sources/Bow/Arrow/Kleisli.swift
Sources/Bow/Typeclasses/Applicative.swift
Sources/Bow/Typeclasses/Functor.swift
Sources/Bow/Typeclasses/Selective.swift
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Data/Resource.swift
Sources/BowEffects/Typeclasses/Bracket.swift
Sources/BowRx/MaybeK.swift
Sources/BowRx/ObservableK.swift
Sources/BowRx/SingleK.swift
Tests/BowEffectsLaws/BracketLaws.swift
Tests/BowEffectsTests/IOTest.swift
Tests/BowLaws/ApplicativeLaws.swift

Add several usability improvements to the library.
- Bracket methods now include labels for `acquire`, `release` and `use` to make them easier to remember.
- Type aliases for `EnvIO`, `RIO` and `URIO` have been added.
- Utilities to built an IO from Either, Validated, Result and Try.
- Added contramap on Kleisli.
- Added the ability to map using key paths on Functor.
- Renamed `Applicative.tupled` to `Applicative.zip`.
- Reordered type arguments on `Applicative` for easier usage.
- Selective methods now include labels for the cases and methods that operate on `F<Bool>` are now instance methods instead of static.

Usability enhancements

---

Sources/BowEffects/Foundation/FileManager.swift

Some methods in `FileManager` are only available in certain versions of iOS. This PR adds the `@available` annotation.

Add available annotations

---

Sources/Bow/Transformers/WriterT.swift
Sources/Bow/Typeclasses/MonadWriter.swift
Tests/BowTests/Transformers/WriterTTest.swift

- Implementation of `censor` for `MonadWriter` was wrong as it was accumulating the transformed stream to its transformation.
- Utilities to work with `Writer` (a.k.a. WriterT<ForId, W, A>) have been added.

Fix censor implementation in MonadWriter

---

Sources/BowEffects/Data/IO.swift

- Rename methods to build an IO.
- Add utility to erase type error information.

Rename IO methods

---

Sources/BowEffects/Foundation/FileManager.swift

Ambiguous use of `removeItem(atPath:)` - conflict with Foundation's definition

Fix signature about `removeItem`

---

.travis.yml
scripts/gen-docs.rb

#427 
We found that by default Travis shallow clones a repository with a depth of 50 commits, which could cause problems if one of the tags that we want to deploy is older than that. In an effort to find the right balance we are setting a depth of 200 here. The Git history is being also deactivated just to have a clean branch for deployments. Additionally, the `0.5.0` tag is being removed from the generated tags, as it being the default one is not necessary to generate it twice.
* Increase git cloning depth to allow that clone to access older tags
* Deactivate the history keeping for the `gh-pages` branch
* Remove 0.5.0 from the list of generated tags, as it's the default one

Docs deployment fixes

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Typeclasses/MonadComprehensions/BindingOperator.swift
Tests/BowEffectsLaws/AsyncLaws.swift
Tests/BowLaws/BindingOperatorOverload.swift

Remove binding instructions of values with no context as it leads to error prone code that does not behave as expected. Removing this leverages the power of the compiler to detect non-homogeneous monad comprehensions.

Remove error prone binding instruction

---

.travis.yml

Bow version 6.0.0 have introduced the need to support various Swift versions, which is only available since Cocoapods 1.7.0 (http://blog.cocoapods.org/CocoaPods-1.7.0-beta/)
Install cocoapods explicitely when deploying docs, which will install latest available Cocoapods version.

Install cocoapods explicitely when deploying docs

---

docs/Gemfile.lock
scripts/gen-docs.rb

Now, after updating the Gemfile dependencies, when the diferent versions are being generated, bundle will complain on the installation not having the dependencies specified in the lockfile form that version... So, to avoid that, we are removing the lockfile each version site is being generated.
* Remove lockfiles to avoid conflicts in case it differs between versions

Remove lockfiles to avoid conflicts in case it differs between versions

---

contents/Documentation/Effects.playground/Pages/Running side effects.xcplaygroundpage/Contents.swift

An incorrect space char is causing a title in the _Running Side Effects_ page to not be properly styled: 
https://bow-swift.io/next/docs/effects/running-side-effects/
If the character gets analyzed it's the standard Unicode space (https://unicode.org/cldr/utility/character.jsp?a=0020), but somehow it is not, as it can be checked in this commit diff...
:man_shrugging: :man_shrugging: :man_shrugging: 
https://bow-swift.io/next/docs/effects/running-side-effects/
This PR set a proper space on that title.

Fix bad space char at docs

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Instances/BoolInstances.swift
Sources/Bow/Instances/NumberInstances.swift
Sources/Bow/Typeclasses/Semiring.swift
Sources/BowOptics/Fold.swift
Tests/BowLaws/SemiringLaws.swift
Tests/BowOpticsTests/FoldTest.swift
Tests/BowTests/Instances/BoolInstancesTest.swift
Tests/BowTests/Instances/NumberInstancesTest.swift

Resolve #448
Also add `Semiring` instances for `Bool` and Numbers
For `Bool`, I also update `Monoid` instance that define `&&` and `true`
as `Monoid` which is more multiplicative. So I change to `||` and
`false` for `Monoid` and add `&&` and `true` to `Semiring`
multiplication

Add Semiring typeclass

---

Package.resolved

This PR commits the `Package.resolved` file generated by `swift build`. It is an auto-generated file. 
According to the [proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0175-package-manager-revised-dependency-resolution.md#proposed-solution),
> The version of every resolved dependency will be recorded in a Package.resolved file in the top-level package, and when this file is present in the top-level package it will be used when performing dependency resolution, rather than the package manager finding the latest eligible version of each package. 
> When this file is checked in, it allows a team to coordinate on what versions of the dependencies they should use. If this file is gitignored, each user will separately choose when to get new versions based on when they …

Commit package.resolved to the repo

---

Sources/Bow/Data/Option.swift
Sources/Bow/Typeclasses/Monoidal.swift
Tests/BowLaws/MonoidalLaws.swift
Tests/BowTests/Data/OptionTest.swift

Closes #450 
This PR adds the Monoidal type class and Monoidal laws. Also includes the implementation for Option monoidal and tests.
The Monoidal laws verify the left and right identity; `fa.product(identity) == identity.product(fa) == identity`
Nothing remarkable, it follows the same pattern as others.

Add monoidal type class

---

Bow.xcodeproj/project.pbxproj

After last PRs were merged, some of the files were not properly added to their corresponding targets, causing build failures when the project is build from Xcode. It does not happen on CI since they are still placed in the correct folder and the SPM is able to find them.
- Adds files to the corresponding targets.
- Deletes a reference to a non-existing file.

Fix project

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Typeclasses/Divisible.swift
Tests/BowLaws/DivisibleLaws.swift

https://github.com/bow-swift/bow/issues/452
This PR adds Divisible typeclass and laws.
`Divisible` extends `Divide` to add `conquer` which returns a `Kind<Self, A>` instance.
The laws check the left and right identity.

Add Divisible typeclass and laws

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/Co.swift
Sources/Bow/Data/Pairing.swift
Tests/BowGenerators/Data/Co+Gen.swift
Tests/BowTests/Data/CoTest.swift

This work should help with #236 , though I'm not aware of a specific issue for Co and Pairing. I'm creating this PR as suggested here: https://twitter.com/tomasruizlopez/status/1190692278421086209
Add Co and Pairing types to Bow as well as introduce the first implementation of Rank2 types that fully works. As implemented right now, Day's functions that should have a higher-rank forall don't work properly.
I tried _a lot_ of ways to get rank2 typing to work in Swift, and the method here is the one that worked the best.
Here are some of the ways I've attempted that I remember for future reference:
1. Look at Day both in the Arrow and Bow projects and try to do rank2 types in a similar way -- this failed because of an issue with subclassing and generics in Swift and the lack of abstract …

Add Co, Pairing (a few Rank2 types)

---

Sources/Bow/Typeclasses/Decidable.swift
Sources/Bow/Typeclasses/Divide.swift
Sources/Bow/Typeclasses/Monoidal.swift
Sources/Bow/Typeclasses/Semigroupal.swift

Reformat API docs of some of the newly introduced type classes to make them consistent with the rest of API docs in the library.

Reformat API docs for some type classes

---

Sources/BowEffects/Typeclasses/Concurrent.swift

This PR extends `Traverse` when the inner effect is `Concurrent`. That way, the traversing and collection of effects can be done in parallel. The following methods have been added:
- `parTraverse`
- `parSequence`
- `parFlatTraverse`

Extend Traverse to do parallel operations

---

docs/_includes/_nav.html
docs/_includes/_navigation-api-versions.html
docs/_includes/_navigation-doc-versions.html
docs/_includes/_sidebar-doc-versions.html

Just noticed that the pipe operator was being used incorrectly when looping through collections in some website layouts.
https://shopify.github.io/liquid/tags/iteration/
Remove that bad usage, that was causing warning on site generation builds.
Just removed the pipes where they were not necessary.

Remove pipe operator when using offset

---

Sources/Bow/Typeclasses/Monad.swift

This PR adds the `flatTap` operation to perform an effect based on the output of other effect, and discard its result. It is useful, for instance, to log things:
```swift
let io: IO<Error, String> = ...
let result = io.flatTap { str in ConsoleIO.print(str) } // result still contains the same String, but also prints it
```

Add flatTap operation to Monad

---

Sources/Bow/Data/Co.swift
Sources/Bow/Data/Pairing.swift
Tests/BowGenerators/Data/Co+Gen.swift
Tests/BowTests/Data/CoTest.swift

Hide public visibility of `Co` and `Pairing` as they are still not fully stable (implementation is not 100% finished) in preparation of the upcoming release. We will re-assess their visibility once we finish working on their implementation.

Hide visibility of unstable data types

---

Bow.xcodeproj/project.pbxproj
Bow.xcodeproj/xcshareddata/xcschemes/Bow-Effects.xcscheme
Sources/Bow/Data/Either.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Data/Internal/DispatchTimeInterval+Extensions.swift
Sources/BowEffects/Data/Schedule.swift

Current implementation does not have a mechanism to retry or repeat effectful computations based on `IO` or `EnvIO`.
Create a composable way of specifying retrial/repeat policies to re-run effectful computations. I used [ZIO](https://github.com/zio/zio/blob/fae35db0dd8c8fb89e52a76bdf2f22d63a81a4e1/core/shared/src/main/scala/zio/Schedule.scala) as an inspiration to achieve this.
Functions to `retry` and `repeat` have been added to `EnvIO` and `IO` (the latter delegates on the former). These functions receive a `Schedule` that dictates if the effect needs to be reapplied or not.
Primitive `Schedules` have been added, where the most prominent ones are:
- `Schedule.recurs(n)`: recurs `n` times.
- `Schedule.forever()`: recurs forever.
- `Schedule.spaced(time)`: recurs forever, spacing each …

Scheduling policies to retry and repeat effectful computations

---

.travis.yml
Bow.xcodeproj/project.pbxproj
Bow.xcodeproj/xcshareddata/xcschemes/Bow-Effects.xcscheme
Sources/Bow/Data/Either.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Data/Internal/DispatchTimeInterval+Extensions.swift
Sources/BowEffects/Data/Schedule.swift
Sources/BowEffects/Typeclasses/Concurrent.swift
Sources/BowEffects/Typeclasses/ConcurrentTraverse.swift
Sources/BowRx/MaybeK.swift
Sources/BowRx/ObservableK.swift
Sources/BowRx/SingleK.swift
Tests/BowEffectsTests/EnvIOTest.swift

`EnvIO` was scattered through the `IO` file and starting to grow too big. Also, some instances can be provided for `Kleisli` when `F` has instances for some effect type classes.
- Extract `EnvIO` to its own file.
- Provide type class instances for `Kleisli` when `F` has instances for `MonadDefer`, `Async` and `Concurrent`.
- Test laws for the given instances.

Extract EnvIO and provide some instances

---

Bow.xcodeproj/project.pbxproj
Sources/BowEffects/Data/Array+TraverseConcurrent.swift

Project `parTraverse`, `parSequence` and `parFlatTraverse` on `Array`, relying on the implementation of these methods on `ArrayK`.

Add utilities to traverse an array concurrently

---

Bow.xcodeproj/project.pbxproj
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Data/Internal/DispatchQueue+Extensions.swift
Sources/BowEffects/Data/Internal/Queue.swift
Tests/BowEffectsLaws/AsyncLaws.swift

We have detected when the user uses `IO.handleErrorWith` execution always continue on the main thread and it is performed at this moment.
It is happening because internally `IO.handleErrorWith` is using `attempt(on: .main)` to perform the side effects and resolve the handle at this moment.

[Bug] handleErrorWith IO::ApplicativeError

---

Sources/BowEffects/Foundation/ConsoleIO.swift

Do not execute effects in Console before running unsafe the `IO`

suspended print in ConsoleIO

---

.travis.yml

Latest builds are failing due to an error:
```bash
$ gem update --system
Updating rubygems-update
Successfully installed rubygems-update-3.1.1
Installing RubyGems 3.1.1
Successfully built RubyGem
Name: bundler
Version: 2.1.0
File: bundler-2.1.0.gem
bundler's executable "bundle" conflicts with /Users/travis/.rvm/rubies/ruby-2.6.4/bin/bundle
Overwrite the executable? [yN]  
```
Fix those Travis builds problems.
We are using the `-v` option to try to tell the system to install an exact versions, so we don't need to update the Ruby environment globally.

Set exact versions installing Travis builds Ruby dependencies

---

scripts/gen-docs.rb

After the last release, we didn't update the version selector for docs.
Set version 0.7.0 as the current version.

Set version 0.7.0 as the current version for docs

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Typeclasses/ComonadEnv.swift
Sources/Bow/Typeclasses/ComonadStore.swift
Sources/Bow/Typeclasses/ComonadTraced.swift

Creates the following type classes for Comonads:
- [ComonadStore](http://support.hfm.io/1.6/api/comonad-5.0.2/Control-Comonad-Store.html)
- [ComonadEnv](http://support.hfm.io/1.6/api/comonad-5.0.2/Control-Comonad-Env.html)
- [ComonadTraced](http://support.hfm.io/1.6/api/comonad-5.0.2/Control-Comonad-Traced.html)
Implementation is based on the Haskell package for Comonads that you can check in the links above.

Comonad Type classes

---

Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift

Add `bimap` to data type `EnvIO` and `IO` to transform the type arguments.
- `fe` function to transform error type argument
- `fa` function to transform output type argument.
```swift
func bimap<E: Error, EE: Error, B>(_ fe: @escaping (E) -> EE, _ fa: @escaping (A) -> B) -> EnvIO<D, EE, B>
```

Add bimap to EnvIO + IO

---

Sources/Bow/Arrow/Kleisli.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Tests/BowLaws/MonadLaws.swift

Oftentimes we have to write the following boilerplate to create an `EnvIO`:
```swift
EnvIO { env in
IO.invoke { 
// Do some side-effectful operation using env
}
}
```
This PR lifts the `invoke*` constructors in `IO` to `EnvIO`, in order to avoid that double nesting to perform the side effects, improving ergonomics of the library.

EnvIO constructors

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Transformers/EnvT.swift
Sources/Bow/Typeclasses/ComonadEnv.swift
Tests/BowLaws/ComonadEnvLaws.swift
Tests/BowLaws/ComonadStoreLaws.swift
Tests/BowLaws/ComonadTracedLaws.swift
Tests/BowTests/Transformers/EnvTTest.swift
Tests/BowTests/Transformers/StoreTTest.swift
Tests/BowTests/Transformers/TracedTTest.swift

Being able to test instances of Comonad Transformer type classes (namely `ComonadEnv`, `ComonadStore` and `ComonadTraced`) satisfy their laws.
We use Property-based Tests to encode the properties these implementations must have. Making use of arbitrary generators, we create inputs for these functions that we can verify later for each implementation (`EnvT`, `StoreT` and `TracedT`  respectively).

Add Comonad Transformer Laws

---

Documentation.app/Contents/MacOS/Podfile.lock
Sources/Bow/Arrow/Kleisli.swift
Sources/Bow/Data/Co.swift
Sources/Bow/Data/Pairing.swift
Sources/Bow/Data/Reader.swift
Sources/Bow/Syntax/Predef.swift
Sources/Bow/Transformers/StateT.swift
Sources/BowOptics/Getter.swift
Sources/BowOptics/Lens.swift
Tests/BowGenerators/Transformers/StateT+Gen.swift
Tests/BowTests/Data/CoTest.swift
Tests/BowTests/Transformers/StateTTest.swift

Add instances for known pairings of functors:
- Id / Id
- StateT / StoreT
- WriterT / TracedT
- ReaderT / EnvT
The implementation of these pairings is based on their implementation in PureScript that can be checked [here](https://github.com/arthurxavierx/purescript-comonad-ui-todos/blob/master/src/Data/Functor/Pairing.purs).
This PR also refactors the `StateT` transformer to remove the extra wrapping of the stateful function in an `F` context and makes it like the Haskell or PureScript implementations. Without this change, the pairing with StoreT would not be possible.

Add Pairings of Functors

---

Bow.xcodeproj/project.pbxproj
Documentation.app/Contents/MacOS/Documentation.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
Documentation.app/Contents/MacOS/Effects.playground/Pages/Retrying and repeating effects.xcplaygroundpage/Contents.swift
Sources/BowEffects/Data/IO.swift

`IO` has a property to wrap it into an `EnvIO` that sets `Any` as dependency type, but this limits type inference and composability.
Instead of using `Any`, a generic type `D` is used, so the caller determines this type, making it easier to compose.

Generalize function to convert from IO to EnvIO

---

Sources/Bow/Data/NonEmptyArray.swift

Fix the inner `NEA` when a traverse operation is applied to avoid nested `Kind`s.

Add convenience traverse to NEA

---

Documentation.app/Contents/MacOS/Effects.playground/Pages/Handling errors.xcplaygroundpage/Contents.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift

Provide a convenience method to run an `EnvIO` operation, providing its dependencies. It is a wrapper of two calls (`provide` + `unsafeRun`).
This PR also deprecates `IO.mapLeft` in favor of `IO.mapError`. Both are maintained until the next version is released.

EnvIO utilities to run an operation

---

Sources/Bow/Syntax/Predef.swift
Sources/BowEffects/Typeclasses/Bracket.swift
Tests/BowEffectsLaws/BracketLaws.swift

As per [this issue in Arrow](https://github.com/arrow-kt/arrow/issues/1996) I just checked and it seems that Bow suffers from the same issue (unless I messed up with the tests 😅).
What changed:

Bracket's guarantee does not work for errors

---

Documentation.app/Contents/MacOS/Effects.playground/Pages/Handling errors.xcplaygroundpage/Contents.swift
Sources/Bow/Arrow/Function1.swift
Sources/Bow/Data/Co.swift
Sources/Bow/Transformers/TracedT.swift
Sources/Bow/Typeclasses/ComonadTraced.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Tests/BowGenerators/Data/Co+Gen.swift
Tests/BowLaws/MonadWriterLaws.swift
Tests/BowTests/Data/CoTest.swift

Generalize `Co` to a transformer `CoT`, that provides a Monad transformer for a given `Comonad`. From there, we can derive instances based on their duals:
- Given a `ComonadEnv` instance, derive the `MonadReader` instance for `CoT`.
- Given a `ComonadStore` instance, derive the `MonadState` instance for `CoT`.
- Given a `ComonadTraced` instance, derive the `MonadWriter` instance for `CoT`.
Deriving this last instance made me realize that `ComonadTraced` needed some dual methods to the ones present in `MonadWriter`, which were added in this PR.

Add Co Transformer and derive instances from their duals

---

Bow.xcodeproj/project.pbxproj
Documentation.app/Contents/MacOS/Effects.playground/Pages/Handling errors.xcplaygroundpage/Contents.swift
Sources/Bow/Arrow/Function1.swift
Sources/Bow/Data/Co.swift
Sources/Bow/Data/Pairing.swift
Sources/Bow/Transformers/TracedT.swift
Sources/Bow/Transformers/WriterT.swift
Sources/Bow/Typeclasses/ComonadTraced.swift
Sources/Bow/Typeclasses/MonadReader.swift
Sources/Bow/Typeclasses/MonadState.swift
Sources/Bow/Typeclasses/MonadWriter.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Tests/BowGenerators/Data/Co+Gen.swift
Tests/BowLaws/MonadWriterLaws.swift
Tests/BowTests/Data/CoTest.swift
Tests/BowTests/Data/PairingTest.swift

This PR tests the Pairing combinations for State/Store, Writer/Traced and Reader/Env. While writing the tests, some improvements to the ergonomics of the projected methods of MonadReader, MonadWriter and MonadState were found and applied. Also, some utility methods for Co and Pairing were added.
Tests are based on examples found on [this paper](https://pdfs.semanticscholar.org/31b9/1969215a46f5d44298e1c1e67872edd7ae77.pdf).

Add tests for Pairing

---

Bow.xcodeproj/project.pbxproj
Bow.xcodeproj/xcshareddata/xcschemes/Bow.xcscheme
Bow.xcodeproj/xcshareddata/xcschemes/BowAllTests.xcscheme
Tests/BowAllTests/BowTests.xctestplan
Tests/BowAllTests/Info.plist

https://github.com/bow-swift/bow/issues/243
Run the bunch of tests for only one target: `BowAllTests`
Created a new target `BowAllTests` for testing and adding a new `xctestplan` to group all of them.
I have checked `Cocoa Pods`, `SPM`, and `Carthage` has not been broken with the changes.

Add target for launch the whole bow tests

---

Sources/Bow/Transformers/EnvT.swift
Sources/Bow/Transformers/StateT.swift
Sources/Bow/Transformers/StoreT.swift
Sources/Bow/Transformers/TracedT.swift

Some aliases for State are not correct with respect to their corresponding ones on StateT.

Fix type aliases for State

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/Action.swift
Sources/Bow/Data/Moore.swift
Sources/Bow/Data/Pairing.swift
Tests/BowTests/Data/PairingTest.swift

Add Action (dual monad of Moore comonad) and its corresponding Pairing instance.
Action is implemented using Co for Moore, which automatically provides a pairing dual monad for a given comonad. Convenience constructors are added in order to work nicely with Actions.

Add Action and its Pairing with Moore

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/CoSum.swift
Sources/Bow/Data/Pairing.swift
Sources/Bow/Data/Sum.swift
Tests/BowTests/Data/PairingTest.swift

- Fix an issue with the implementation of `coflatMap` for Sum.
- Provide missing methods for Sum.
- Provide its dual Monad, CoSum.
- Provide convenience aliases for SumOpt and CoSumOpt.
- Provide Pairings between Sum and CoSum.

Enhace Sum Comonad with its dual Monad

---

Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Typeclasses/UnsafeRun.swift

Improve the usability of the methods provided in `UnsafeRun`, moving from static to instance methods on `Kind`. This way, we can abstract over the execution of an effect. The previous version was:
```swift
Kind<F, A>.runBlocking(on: .main) { fa }
Kind<F, A>.runNonBlocking(on: .main, { fa }) { result in ... }
```
With this version, it becomes:
```swift
fa.runBlocking(on: .main)
fa.runNonBlocking(on: .main) { result in ... }
```
Callbacks are also optional in non-blocking / async executions.

Enhance UnsafeRun methods

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/Pairing.swift
Sources/Bow/Data/Puller.swift
Sources/Bow/Data/Zipper.swift
Tests/BowTests/Data/PairingTest.swift
Tests/BowTests/Data/ZipperTest.swift

- Provide a dual monad for Zipper, named Puller.
- Provide methods to construct Puller actions.
- Provide a pairing between both.
The implementation is obtained for free using `Co`.

Add Puller Monad as a dual of Zipper Comonad

---

Sources/Bow/Data/Endo.swift

- Closes #537.
Add missing documentation to the API Reference of `Endo`.

Document Endo API

---

Sources/Bow/Typeclasses/ComonadEnv.swift
Sources/Bow/Typeclasses/ComonadStore.swift
Sources/Bow/Typeclasses/ComonadTraced.swift
Sources/Bow/Typeclasses/ComonadTrans.swift

- Closes #526.
- Closes #527.
- Closes #528.
- Closes #529.
Document API Reference for the type classes for Comonad Transformers.

Comonad Transformers Type Classes API Reference

---

Documentation.app/Contents/MacOS/FP concepts.playground/Pages/Data types.xcplaygroundpage/Contents.swift

Some content in the website was rendering as `&lt;` and `&gt;` because it was embedded in backticks. This PR fixes it.

Small rendering issue

---

Sources/Bow/Typeclasses/Monoid.swift
Sources/Bow/Typeclasses/Semigroup.swift

The implementation of `combineAll` for Semigroup is not safe, as passing 0 values will make it crash. Semigroup always needs at least one value.
- Force having at least one element in `combineAll` in the signature of the function.
- Provide an additional `combineAll` function in Monoid that can accept 0 or more values, using the `empty` value in case no values are combined.

Semigroup and Monoid enhancements

---

Sources/Bow/Data/Array.swift
Sources/Bow/Typeclasses/Applicative.swift
Sources/Bow/Typeclasses/ComonadTrans.swift
Sources/Bow/Typeclasses/Foldable.swift
Sources/Bow/Typeclasses/Traverse.swift
Tests/BowTests/Data/ArrayTest.swift

Some type classes, especially the ones dealing with multiple effects, were having inference problems as the nested effects are fixed to `Kind` and therefore we cannot pass subclasses of them (their fixed form). This PR relaxes those constraints to ease type inference and have a more flexible API that is more ergonomic.

Improve type inference in some type classes

---

CONTRIBUTING.md

Update contribution guidelines to remove reference to Travis, as we are no longer using it, and add some minor details.

Update Contribution guidelines

---

scripts/gen-docs.rb

Closes #128
Fix Dash URL for API References
Internally `Jazzyl` is using `URI::join` class, you can read the API reference [here](https://apidock.com/ruby/URI/join/class).
Inside `docset_builder.rb` we can find the next line:
```ruby
URI.join(config.root_url, "docsets/#{source_module.name}.tgz")
```
So we need to send a `root_url` finished in `/` to generate a valid `URL` - in another case, when the lib invoke `.to_s` will lose the last component path (in our case `api-docs`)

Fix dash_url valid link to download doc .tgz

---

Sources/Bow/Arrow/Cokleisli.swift
Sources/Bow/Arrow/Function0.swift
Sources/Bow/Arrow/Function1.swift
Sources/Bow/Arrow/FunctionK.swift

Cleanup code in the Arrow folder in the Core module by:

Cleanup Arrow folder in Bow Core

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/ArrayK.swift
Sources/Bow/Data/Co.swift
Sources/Bow/Data/Const.swift
Sources/Bow/Data/Coreader.swift
Sources/Bow/Data/Day.swift
Sources/Bow/Data/Dictionary.swift
Sources/Bow/Data/DictionaryK.swift
Sources/Bow/Data/Either.swift
Sources/Bow/Data/EitherK.swift
Sources/Bow/Data/Eval.swift
Sources/Bow/Data/Id.swift
Sources/Bow/Data/Ior.swift
Sources/Bow/Data/Moore.swift
Sources/Bow/Data/NonEmptyArray.swift
Sources/Bow/Data/Option.swift
Sources/Bow/Data/Result.swift
Sources/Bow/Data/Set.swift
Sources/Bow/Data/SetK.swift
Sources/Bow/Data/Sum.swift
Sources/Bow/Data/Try.swift
Sources/Bow/Data/Validated.swift
Sources/Bow/Data/Zipper.swift

Cleanup code in the Data folder in the Core module by:

Cleanup Data folder in Core module

---

Sources/Bow/Instances/BoolInstances.swift
Sources/Bow/Instances/NumberInstances.swift
Sources/Bow/Instances/OptionInstances.swift
Sources/Bow/Instances/StringInstances.swift

Cleanup code in the Instances folder in the Core module by:

Cleanup Instances Folder in Core module

---

Sources/Bow/Syntax/BooleanFunctions.swift
Sources/Bow/Syntax/Curry.swift
Sources/Bow/Syntax/Memoization.swift
Sources/Bow/Syntax/PartialApplication.swift
Sources/Bow/Syntax/Predef.swift
Sources/Bow/Syntax/Reverse.swift

Cleanup code in the Syntax folder in the Core module by:

Cleanup Syntax folder in Core module

---

Sources/Bow/Transformers/EitherT.swift
Sources/Bow/Transformers/EnvT.swift
Sources/Bow/Transformers/OptionT.swift
Sources/Bow/Transformers/StateT.swift
Sources/Bow/Transformers/StoreT.swift
Sources/Bow/Transformers/TracedT.swift
Sources/Bow/Transformers/WriterT.swift

Cleanup code in the Transformers folder in the Core module by:

Cleanup Transformers folder in Core module

---

Sources/BowEffects/Foundation/ConsoleIO.swift
Sources/BowEffects/Foundation/FileManager.swift
Sources/BowEffects/Foundation/URLSession.swift

Cleanup code in the Foundation folder in the Effects module by:

Cleanup Foundation folder in Effects module

---

Sources/BowEffects/Typeclasses/Async.swift
Sources/BowEffects/Typeclasses/Bracket.swift
Sources/BowEffects/Typeclasses/Concurrent.swift
Sources/BowEffects/Typeclasses/ConcurrentEffect.swift
Sources/BowEffects/Typeclasses/ConcurrentTraverse.swift
Sources/BowEffects/Typeclasses/Effect.swift
Sources/BowEffects/Typeclasses/EffectComprehensions.swift
Sources/BowEffects/Typeclasses/MonadDefer.swift
Sources/BowEffects/Typeclasses/UnsafeRun.swift

Cleanup code in the Typeclasses folder in the Effects module by:

Cleanup Typeclasses folder in Effects module

---

Sources/BowEffects/Data/Array+TraverseConcurrent.swift
Sources/BowEffects/Data/Atomic.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/IO.swift
Sources/BowEffects/Data/Internal/Dictionary+Extensions.swift
Sources/BowEffects/Data/Ref.swift
Sources/BowEffects/Data/Resource.swift

Cleanup code in the Data folder in the Effects module by:

Cleanup Data folder in Effects module

---

Tests/BowGenerators/Arrow/Function0+Gen.swift
Tests/BowGenerators/Arrow/Function1+Gen.swift
Tests/BowGenerators/Arrow/Kleisli+Gen.swift
Tests/BowGenerators/Data/ArrayK+Gen.swift
Tests/BowGenerators/Data/Const+Gen.swift
Tests/BowGenerators/Data/Day+Gen.swift
Tests/BowGenerators/Data/DictionaryK+Gen.swift
Tests/BowGenerators/Data/Either+Gen.swift
Tests/BowGenerators/Data/EitherK+Gen.swift
Tests/BowGenerators/Data/Eval+Gen.swift
Tests/BowGenerators/Data/Id+Gen.swift
Tests/BowGenerators/Data/Ior+Gen.swift
Tests/BowGenerators/Data/Moore+Gen.swift
Tests/BowGenerators/Data/NonEmptyArray+Gen.swift
Tests/BowGenerators/Data/Option+Gen.swift
Tests/BowGenerators/Data/Sum+Gen.swift
Tests/BowGenerators/Data/Try+Gen.swift
Tests/BowGenerators/Data/Validated+Gen.swift
Tests/BowGenerators/Data/Zipper+Gen.swift
Tests/BowGenerators/Transformers/EitherT+Gen.swift
Tests/BowGenerators/Transformers/EnvT+Gen.swift
Tests/BowGenerators/Transformers/OptionT+Gen.swift
Tests/BowGenerators/Transformers/StateT+Gen.swift
Tests/BowGenerators/Transformers/StoreT+Gen.swift
Tests/BowGenerators/Transformers/TracedT+Gen.swift
Tests/BowGenerators/Transformers/WriterT+Gen.swift
Tests/BowGenerators/Typeclasses/ArbitraryK.swift

Cleanup code in the Core Generators module by:

Cleanup Core Generators

---

Bow.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.resolved
Package.swift

Currently, Bow depends on SwiftCheck to write tests and exposes some libraries for testing laws. SwiftCheck exposes dependencies that are only used for testing, but end up being fetched every time Bow is imported. One of this dependencies causes SwiftUI previews not to load at all because it encounters compilation errors when compiling this dependency.
Given the transitive dependencies for SwiftCheck are only used for testing, they should be removed. Therefore, as Swift Package Manager still does not allow to specify a dependency is only for testing, we have created a fork of SwiftCheck, where the `Package.swift` is modified to remove the test targets and the dependencies. The `Package.swift` in Bow now depends on this fork. Consumers of Bow will not fetch the transitive dependencies …

Remove transitive test-only dependencies

---

Sources/BowEffects/Data/IO.swift

Introducing trampolining broke the parallelism in IO, as execution is sequenced in the suspension induced by the Trampoline.
This PR brings back the parallelism to `race`, `parMap2` and `parMap3` implementations in `IO`.

Fix IO parallelism

---

Sources/Bow/Arrow/Kleisli.swift
Sources/BowEffects/Data/EnvIO.swift
Sources/BowEffects/Data/Ref.swift
Sources/BowEffects/Data/Resource.swift

In order to enhance the ergonomics of using `Ref` and `Resource` when they are backed by `IO`, a couple of type aliases are introduced.
Besides this, `foldM` is moved from `EnvIO` to `Kleisli`, as it is applicable on more types than only `EnvIO`. A utility `foldA` is added as an alias to `foldM` for non-effectful functions.

Add aliases for Ref and Resource

---

.github/workflows/deploy-docs.yml
.github/workflows/nef-compile.yml
.github/workflows/swift.yml
Bow.podspec
Bow.xcodeproj/project.pbxproj
Bow.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
BowEffects.podspec
BowEffectsGenerators.podspec
BowEffectsLaws.podspec
BowFree.podspec
BowFreeGenerators.podspec
BowGenerators.podspec
BowGeneric.podspec
BowLaws.podspec
BowOptics.podspec
BowOpticsLaws.podspec
BowRecursionSchemes.podspec
BowRx.podspec
BowRxGenerators.podspec
Documentation.app/Contents/MacOS/Documentation.xcodeproj/project.pbxproj
Documentation.app/Contents/MacOS/Podfile.lock
Package.swift
Tests/BowOpticsTests/PrismTest.swift
Tests/BowOpticsTests/TestDomain.swift

Fix Xcode project to support Swift 5.2+. Also, if solves a bug in enums -previous version of Swift 5.2- it affects to auto-prisms.
**nef compiler** is failing because we need to release a new nef version to support link to XCTestSwiftSupport lib [currently work in progress]

Update swift5 2

---

Sources/Bow/Arrow/Cokleisli.swift
Sources/Bow/Arrow/Function0.swift
Sources/Bow/Arrow/Function1.swift
Sources/Bow/Arrow/FunctionK.swift
Sources/Bow/Arrow/Kleisli.swift
Sources/Bow/Data/Endo.swift
Sources/Bow/Transformers/TracedT.swift
Sources/Bow/Typeclasses/Functor.swift

Take advantage of features introduced in Swift 5.2, such as:
- KeyPaths as functions: this was already supported, in some types in Bow, so these specific overloads are removed as the default, function-based ones are compatible with KeyPaths.
- `callAsFunction`: types wrapping functions include this feature to be able to be invoked as a function. For instance, a Kleisli function can be invoked as `kleisli(x)` instead of `kleisli.run(x)`.

Leverage Swift 5.2 features

---

Sources/BowEffects/Data/Internal/Queue.swift

Remove insecure code in `Queue`. 
Changes:
1. **sync** work: in case of **unknown** thread, we will run work in a given queue.
2. `DispatchQueue.currentLabel` gives you a random value. 
**BowEffectsLaws** guarantees we are using the Queue constructors (internally in the lib)

Queue sync operation

---

.github/workflows/deploy-docs.yml
.github/workflows/nef-compile.yml
Sources/Bow/Typeclasses/Foldable.swift

Make bow compatibles with Swift Playgrounds. Fix foldable inference in `reduceRightToOption` method.

Swift playgrounds

---

README.md
Sources/Bow/Typeclasses/MonadError.swift
Sources/BowEffects/Data/IO.swift

This PR fixes a bug in IO resources execution. `BracketIO` should execute `release` after `use` execution has been completed.

BracketIO - defer execution

---

Sources/BowOptics/Prism.swift

#601 
Add *or* combinator to PPRism.
I'm wondering what are the right properties to test here. It seems to me that if lens composition is a product in some category, this is probably the coproduct (or viceversa?). Unfortunately I haven't found any info after a quick search. If you have any clue or reference please let me know!

Add or method to PPrism

---

README.md

Enable `try it with iPad` badge in Bow repository.
- **Repo** Bow
- **Tag** 0.8.0

Add try-with-ipad badge

---

Sources/Bow/Data/Option.swift
Tests/BowTests/Data/OptionTest.swift

Adds an ability to use nil values where `Option<A>` values are expected, converting them to `Option<A>.none()` automatically. 
Works in assignments, function call arguments, function default argument values, etc.
```swift
let a: Option<A> = nil 
// is equivalent to
let a: Option<A> = Option.none()
```
```swift
func test(a: Option<A>, b: Option<B> = nil) { ... }
test(nil) 
// is equivalent to
func test(a: Option<A>, b: Option<B> = Option.none()) { ... }
test(Option.none()) 
```
Make Bow's `Option` type feel more native to Swift, similar to how `Optional` behaves in Bow Lite.
Surprisingly simple conformance to `ExpressibleByNilLiteral` was enough to get both the nil assignment to act as `Option<A>.none()` assignment *and* default initialization values for `Option<A>` variables. I did have …

Conform Option to ExpressibleByNilLiteral protocol

---

Package.swift
Tests/BowLaws/ApplicativeLaws.swift

#613: Missing Generic module
#610: Unable to run tests on Xcode 12 due to a timeout in type inference
- Refactor `Package.swift` and include missing package `BowGeneric`.
- Add type annotations to avoid type inference timeouts.

Include Generic module in Package

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Arrow/FunctionK.swift
Sources/BowFree/Free.swift
Sources/BowFree/FunctionK+Free.swift
Tests/BowFreeGenerators/Free+Gen.swift
Tests/BowFreeTests/FreeTest.swift
Tests/BowGenerators/Typeclasses/ArbitraryK.swift

Closes #286 
Provide a better, more robust implementation for `Free`.
Free is a type that, given any Functor, it is able to provide a Monad for it. This Monad can be later interpreted into different, less restrictive Monads. Free is modeled as a sum type where the two cases roughly correspond to the `pure` and `flatten` methods in Monad. From there, instances of Functor, Applicative, Selective, and Monad are able to be provided.
This PR also includes some utilities in terms of natural transformations (extensions to FunctionK) that will help in the interpretation of Free Monads.
Type class laws and general behavior of the Free implementation are tested.

Revamp Free

---

Sources/Bow/Data/Ior.swift
Sources/Bow/Transformers/WriterT.swift
Tests/BowLaws/MonadLaws.swift
Tests/BowTests/Data/IorTest.swift

I added two new laws to test `tailRecM` (I took them [from Scala](https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/FlatMapLaws.scala#L33)).
With the new `tailRecMConsistentFlatMap` law I discovered and fixed bugs in the implementation of `tailRecM` for `Ior` and `WriterT`.
- In `Ior`, when flatMapping on a `Both` value, when the new value is `Right`, we were returning `Both` (correct value is `Right`).
- In `WriterT` we were not combining the old `W` with the new `W` obtained after flatmapping.

New tailRecM laws + Bug fixes 🐞

---

Bow.xcodeproj/project.pbxproj
Sources/BowFree/Program.swift
Tests/BowFreeGenerators/Program+Gen.swift
Tests/BowFreeTests/ProgramTest.swift

(Re)Introduce[1] Free-er monads in Bow. `Program` allows you to get a monad from any type constructor. Unlike `Free`, it doesn't require `F` to be a functor, so not only does it defer the evaluation of `flatMap` calls for later interpretation into another monad, but also (unlike Free) defers calls to `map`.
Reference: [free-operational](http://hackage.haskell.org/package/free-operational-0.5.0.0/docs/Control-Monad-Operational-Simple.html)
**Do we need both `Free` and `Program`?**
Yes. When you use `Free`, certain properties can be enforced in the Functor implementation of `F`, meaning that those properties will be fulfilled no matter what interpreter you use later [2].
When you use `Program`, you cannot enforce properties on the Functor implementation of F, because it's just not a …

Introduce Program type for free-er monads

---

Sources/Bow/Transformers/WriterT.swift

#640 
Increase awareness that `Writer<A, B>` is just `(A, B)`. To do so we add a typealias `Pair` to `Writer` and a couple of convenience methods.

Add Pair typealias to Writer

---

.github/workflows/nef-compile.yml

This PR fixes CI about Homebrew fails:
```
Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
fatal: invalid upstream 'origin/master'
fatal: invalid upstream 'origin/master'
```

CI: fix homebrew fails

---

Sources/Bow/Typeclasses/Monad.swift
Tests/BowLaws/MonadLaws.swift

Provide a default implementation of `flatMap` based on `tailRecM`. 
Useful when you want a fully stack safe monad, or when you don't want to specialize the implementation of flatMap.

Add stackSafeFlatMap

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Data/Exists.swift
Tests/BowGenerators/Data/Exists+Gen.swift
Tests/BowTests/Data/ExistsTests.swift

Make `Exists` conform to `CustomStringConvertible` and `CustomDebugStringConvertible`.
`Exists` might not always be truly `CustomStringConvertible`, because the inner type might not conform to `CustomStringConvertible`.
When `Exists` holds a value of an inner type that is not `CustomStringConvertible` it will use `\(fa)` as description.
For `CustomDebugStringConvertible` the behavior is the same.

Make Exists conform to CustomStringConvertible

---

Bow.xcodeproj/project.pbxproj
Sources/Bow/Typeclasses/MonadComprehensions/BindingExpression.swift
Sources/Bow/Typeclasses/MonadComprehensions/BindingOperator.swift
Sources/Bow/Typeclasses/MonadComprehensions/BoundVar.swift
Tests/BowTests/Syntax/MonadComprehensionTest.swift

When using monad comprehensions, `flatMap` is called with values of type `Kind<F, Any>` and erased functions. From a result point of view, this is fine, as checked by the "Monad comprehensions equivalence to flatMap"  law.
However, when debugging, the situation is a little weird because if I set a breakpoint on the implementation of `flatMap` for a Monad, I cannot  know what's the inner type of my Monad at that point, because I always see `Kind<F, Any>`.
This PR fixes this.
Instead of erasing to `Any`, `BindingExpression` now uses `Exists`. This allows us to call `flatMap` with the right type, instead of Any.
The test is a little bit weird, but I couldn't think of any other way to test this.

Typed monad comprehensions

---

Sources/BowOptics/AffineTraversal.swift
Sources/BowOptics/Fold.swift
Sources/BowOptics/Getter.swift
Sources/BowOptics/Iso.swift
Sources/BowOptics/Lens.swift
Sources/BowOptics/Prism.swift
Sources/BowOptics/Setter.swift
Sources/BowOptics/Traversal.swift

Remove Kinds from optics.
The only necessary change was to remove the boilerplate associated to the declaration of the optics. This was never used and adds an overhead on the optics. As a result, some of the optics (except for Fold and Traversal) can be implemented as structs.

Remove Kinds from optics
